import type { GeneratorContext, GeneratedFile, ResolvedComponent } from '@ryndesign/plugin-api';
import type { ComposeGeneratorOptions } from './index.js';

export function generateComponentFile(
  comp: ResolvedComponent,
  ctx: GeneratorContext,
  options: ComposeGeneratorOptions
): GeneratedFile[] {
  const { definition } = comp;
  const name = `DS${definition.name}`;
  const pkg = options.packageName ?? 'com.ryndesign.components';
  const files: GeneratedFile[] = [];

  files.push({
    path: `components/${name}.kt`,
    content: generateComposable(comp, options, pkg),
    language: 'kotlin',
  });

  return files;
}

function generateComposable(comp: ResolvedComponent, options: ComposeGeneratorOptions, pkg: string): string {
  const { definition } = comp;
  const name = `DS${definition.name}`;

  let kt = `// Auto-generated by @ryndesign/generator-compose\n`;
  kt += `package ${pkg}\n\n`;

  // Imports
  kt += `import androidx.compose.foundation.background\n`;
  kt += `import androidx.compose.foundation.border\n`;
  kt += `import androidx.compose.foundation.clickable\n`;
  kt += `import androidx.compose.foundation.layout.*\n`;
  kt += `import androidx.compose.foundation.shape.RoundedCornerShape\n`;
  kt += `import androidx.compose.material3.Text\n`;
  kt += `import androidx.compose.runtime.Composable\n`;
  kt += `import androidx.compose.ui.Alignment\n`;
  kt += `import androidx.compose.ui.Modifier\n`;
  kt += `import androidx.compose.ui.draw.alpha\n`;
  kt += `import androidx.compose.ui.draw.clip\n`;
  kt += `import androidx.compose.ui.graphics.Color\n`;
  kt += `import androidx.compose.ui.text.style.TextAlign\n`;
  kt += `import androidx.compose.ui.tooling.preview.Preview\n`;
  kt += `import androidx.compose.ui.unit.dp\n`;
  kt += `import androidx.compose.ui.unit.sp\n\n`;

  // Generate variant enum classes
  for (const [variantName, variant] of Object.entries(definition.variants)) {
    const enumName = `${name}${capitalize(variantName)}`;
    kt += `enum class ${enumName} {\n`;
    kt += `    ${variant.values.map(v => v.toUpperCase()).join(', ')}\n`;
    kt += `}\n\n`;
  }

  // Generate @Composable function
  kt += `@Composable\n`;
  kt += `fun ${name}(\n`;

  // Parameters
  const params: string[] = [];

  for (const [propName, prop] of Object.entries(definition.props)) {
    if (prop.type === 'string') {
      if (prop.required) {
        params.push(`    ${propName}: String`);
      } else {
        const defaultVal = prop.default ? `"${prop.default}"` : '""';
        params.push(`    ${propName}: String = ${defaultVal}`);
      }
    } else if (prop.type === 'boolean') {
      const defaultVal = prop.default ? 'true' : 'false';
      params.push(`    ${propName}: Boolean = ${defaultVal}`);
    } else if (prop.type === 'callback') {
      params.push(`    ${propName}: (() -> Unit)? = null`);
    }
  }

  for (const [variantName, variant] of Object.entries(definition.variants)) {
    const enumName = `${name}${capitalize(variantName)}`;
    params.push(`    ${variantName}: ${enumName} = ${enumName}.${variant.default.toUpperCase()}`);
  }

  // Slot content parameters
  for (const [slotName, slot] of Object.entries(definition.slots)) {
    if (slotName !== 'default') {
      params.push(`    ${slotName}: @Composable (() -> Unit)? = null`);
    }
  }

  params.push(`    modifier: Modifier = Modifier`);

  kt += params.join(',\n');
  kt += `\n) {\n`;

  // Computed values inside the function
  kt += `    val colors = DesignTheme.colors\n\n`;

  // Background color resolution
  const { variantTokens } = comp;
  const defaultSize = definition.variants.size?.default ?? 'md';
  if (definition.variants.variant) {
    const variantEnum = `${name}Variant`;
    kt += `    val backgroundColor = when (variant) {\n`;
    for (const v of definition.variants.variant.values) {
      const token = variantTokens?.[v]?.[defaultSize]?.background;
      if (v === 'ghost' || v === 'outline') {
        kt += `        ${variantEnum}.${v.toUpperCase()} -> Color.Transparent\n`;
      } else if (token && token.$value.type === 'color') {
        const tokenName = token.path.join('_').replace(/[.-]/g, '_');
        kt += `        ${variantEnum}.${v.toUpperCase()} -> colors.${tokenName}\n`;
      } else {
        kt += `        ${variantEnum}.${v.toUpperCase()} -> colors.color_${v}\n`;
      }
    }
    kt += `    }\n\n`;

    kt += `    val contentColor = when (variant) {\n`;
    for (const v of definition.variants.variant.values) {
      const token = variantTokens?.[v]?.[defaultSize]?.textColor;
      if (token && token.$value.type === 'color') {
        const tokenName = token.path.join('_').replace(/[.-]/g, '_');
        kt += `        ${variantEnum}.${v.toUpperCase()} -> colors.${tokenName}\n`;
      } else if (v === 'primary' || v === 'secondary') {
        kt += `        ${variantEnum}.${v.toUpperCase()} -> Color.White\n`;
      } else {
        kt += `        ${variantEnum}.${v.toUpperCase()} -> colors.color_${v}\n`;
      }
    }
    kt += `    }\n\n`;
  }

  // Size resolution
  if (definition.variants.size) {
    const sizeEnum = `${name}Size`;
    const defaultVariant = definition.variants.variant?.default ?? 'primary';

    kt += `    val horizontalPadding = when (size) {\n`;
    for (const s of definition.variants.size.values) {
      const token = variantTokens?.[defaultVariant]?.[s]?.paddingX;
      if (token && token.$value.type === 'dimension') {
        kt += `        ${sizeEnum}.${s.toUpperCase()} -> ${token.$value.value}.dp\n`;
      } else {
        const padding = s === 'sm' ? 12 : s === 'md' ? 16 : 24;
        kt += `        ${sizeEnum}.${s.toUpperCase()} -> ${padding}.dp\n`;
      }
    }
    kt += `    }\n\n`;

    kt += `    val verticalPadding = when (size) {\n`;
    for (const s of definition.variants.size.values) {
      const token = variantTokens?.[defaultVariant]?.[s]?.paddingY;
      if (token && token.$value.type === 'dimension') {
        kt += `        ${sizeEnum}.${s.toUpperCase()} -> ${token.$value.value}.dp\n`;
      } else {
        const padding = s === 'sm' ? 6 : s === 'md' ? 10 : 14;
        kt += `        ${sizeEnum}.${s.toUpperCase()} -> ${padding}.dp\n`;
      }
    }
    kt += `    }\n\n`;

    kt += `    val fontSize = when (size) {\n`;
    for (const s of definition.variants.size.values) {
      const token = variantTokens?.[defaultVariant]?.[s]?.fontSize;
      if (token && token.$value.type === 'dimension') {
        kt += `        ${sizeEnum}.${s.toUpperCase()} -> ${token.$value.value}.sp\n`;
      } else {
        const fs = s === 'sm' ? 14 : s === 'md' ? 16 : 18;
        kt += `        ${sizeEnum}.${s.toUpperCase()} -> ${fs}.sp\n`;
      }
    }
    kt += `    }\n\n`;
  }

  // Corner radius
  kt += `    val cornerRadius = DesignSpacing.component_${definition.name.toLowerCase()}_borderRadius\n`;
  kt += `    val shape = RoundedCornerShape(cornerRadius)\n\n`;

  // Composable body
  kt += `    Row(\n`;
  kt += `        modifier = modifier\n`;
  kt += `            .clip(shape)\n`;
  kt += `            .background(backgroundColor, shape)\n`;

  if (definition.tokenMapping.borderColor) {
    const variantEnum = `${name}Variant`;
    kt += `            .then(\n`;
    kt += `                if (variant == ${variantEnum}.OUTLINE)\n`;
    kt += `                    Modifier.border(1.dp, contentColor, shape)\n`;
    kt += `                else Modifier\n`;
    kt += `            )\n`;
  }

  kt += `            .clickable(enabled = !disabled) { onPress?.invoke() }\n`;
  kt += `            .padding(horizontal = horizontalPadding, vertical = verticalPadding)\n`;
  kt += `            .alpha(if (disabled) 0.6f else 1f),\n`;
  kt += `        horizontalArrangement = Arrangement.Center,\n`;
  kt += `        verticalAlignment = Alignment.CenterVertically,\n`;
  kt += `    ) {\n`;

  // Slot: leading icon
  if (definition.slots.leadingIcon) {
    kt += `        leadingIcon?.invoke()\n`;
    kt += `        Spacer(modifier = Modifier.width(8.dp))\n`;
  }

  // Label
  if (definition.props.label) {
    kt += `        Text(\n`;
    kt += `            text = label,\n`;
    kt += `            color = contentColor,\n`;
    kt += `            fontSize = fontSize,\n`;
    kt += `            textAlign = TextAlign.Center,\n`;
    kt += `        )\n`;
  }

  // Slot: trailing icon
  if (definition.slots.trailingIcon) {
    kt += `        Spacer(modifier = Modifier.width(8.dp))\n`;
    kt += `        trailingIcon?.invoke()\n`;
  }

  kt += `    }\n`;
  kt += `}\n\n`;

  // Preview
  kt += `@Preview(showBackground = true)\n`;
  kt += `@Composable\n`;
  kt += `private fun ${name}Preview() {\n`;
  kt += `    DesignTheme {\n`;
  kt += `        Column(\n`;
  kt += `            modifier = Modifier.padding(16.dp),\n`;
  kt += `            verticalArrangement = Arrangement.spacedBy(12.dp)\n`;
  kt += `        ) {\n`;

  if (definition.variants.variant) {
    const variantEnum = `${name}Variant`;
    for (const v of definition.variants.variant.values) {
      const labelProp = definition.props.label ? `label = "${capitalize(v)}"` : '';
      kt += `            ${name}(${labelProp}${labelProp ? ', ' : ''}variant = ${variantEnum}.${v.toUpperCase()})\n`;
    }
  } else {
    const labelProp = definition.props.label ? `label = "${definition.name}"` : '';
    kt += `            ${name}(${labelProp})\n`;
  }

  kt += `        }\n`;
  kt += `    }\n`;
  kt += `}\n`;

  return kt;
}

function capitalize(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1);
}
