import type { GeneratorContext, GeneratedFile, ResolvedToken, ResolvedValue } from '@ryndesign/plugin-api';
import type { ComposeGeneratorOptions } from './index.js';

export function generateTokenFiles(ctx: GeneratorContext, options: ComposeGeneratorOptions): GeneratedFile[] {
  const files: GeneratedFile[] = [];
  const pkg = options.packageName ?? 'com.ryndesign.tokens';

  files.push(generateColorTokens(ctx, options, pkg));
  files.push(generateDimensionTokens(ctx, pkg));
  files.push(generateTypographyTokens(ctx, pkg));
  files.push(generateThemeFile(ctx, options, pkg));

  return files;
}

function generateColorTokens(ctx: GeneratorContext, options: ComposeGeneratorOptions, pkg: string): GeneratedFile {
  const colorTokens = ctx.tokenSet.tokens.filter(t => t.$type === 'color');
  const darkTheme = ctx.tokenSet.themes.themes['dark'];

  let kt = `// Auto-generated by @ryndesign/generator-compose\n`;
  kt += `package ${pkg}\n\n`;
  kt += `import androidx.compose.ui.graphics.Color\n\n`;

  // Light colors object
  kt += `object LightColors {\n`;
  for (const token of colorTokens) {
    const name = token.path.join('_').replace(/[.-]/g, '_');
    const hex = hexToArgbInt((token.$value as any).hex);
    kt += `    val ${name} = Color(${hex})\n`;
  }
  kt += `}\n\n`;

  // Dark colors object
  if (darkTheme) {
    kt += `object DarkColors {\n`;
    for (const token of colorTokens) {
      const name = token.path.join('_').replace(/[.-]/g, '_');
      const darkToken = darkTheme.tokens.find(t => t.path.join('.') === token.path.join('.'));
      if (darkToken) {
        const hex = hexToArgbInt((darkToken.$value as any).hex);
        kt += `    val ${name} = Color(${hex})\n`;
      } else {
        const hex = hexToArgbInt((token.$value as any).hex);
        kt += `    val ${name} = Color(${hex})\n`;
      }
    }
    kt += `}\n\n`;
  }

  // DesignColors data class
  kt += `data class DesignColors(\n`;
  for (let i = 0; i < colorTokens.length; i++) {
    const token = colorTokens[i];
    const name = token.path.join('_').replace(/[.-]/g, '_');
    const comma = i < colorTokens.length - 1 ? ',' : '';
    kt += `    val ${name}: Color${comma}\n`;
  }
  kt += `)\n\n`;

  // Factory functions
  kt += `fun lightDesignColors() = DesignColors(\n`;
  for (let i = 0; i < colorTokens.length; i++) {
    const token = colorTokens[i];
    const name = token.path.join('_').replace(/[.-]/g, '_');
    const comma = i < colorTokens.length - 1 ? ',' : '';
    kt += `    ${name} = LightColors.${name}${comma}\n`;
  }
  kt += `)\n\n`;

  if (darkTheme) {
    kt += `fun darkDesignColors() = DesignColors(\n`;
    for (let i = 0; i < colorTokens.length; i++) {
      const token = colorTokens[i];
      const name = token.path.join('_').replace(/[.-]/g, '_');
      const comma = i < colorTokens.length - 1 ? ',' : '';
      kt += `    ${name} = DarkColors.${name}${comma}\n`;
    }
    kt += `)\n`;
  }

  return { path: 'DesignColors.kt', content: kt, language: 'kotlin' };
}

function generateDimensionTokens(ctx: GeneratorContext, pkg: string): GeneratedFile {
  const dimTokens = ctx.tokenSet.tokens.filter(t => t.$type === 'dimension');

  let kt = `// Auto-generated by @ryndesign/generator-compose\n`;
  kt += `package ${pkg}\n\n`;
  kt += `import androidx.compose.ui.unit.dp\n`;
  kt += `import androidx.compose.ui.unit.Dp\n\n`;

  kt += `object DesignSpacing {\n`;
  for (const token of dimTokens) {
    const name = token.path.join('_').replace(/[.-]/g, '_');
    const value = (token.$value as any).value;
    kt += `    val ${name}: Dp = ${value}.dp\n`;
  }
  kt += `}\n`;

  return { path: 'DesignSpacing.kt', content: kt, language: 'kotlin' };
}

function generateTypographyTokens(ctx: GeneratorContext, pkg: string): GeneratedFile {
  const typoTokens = ctx.tokenSet.tokens.filter(t => t.$type === 'typography');

  let kt = `// Auto-generated by @ryndesign/generator-compose\n`;
  kt += `package ${pkg}\n\n`;
  kt += `import androidx.compose.ui.text.TextStyle\n`;
  kt += `import androidx.compose.ui.text.font.FontWeight\n`;
  kt += `import androidx.compose.ui.unit.sp\n\n`;

  kt += `object DesignTypography {\n`;
  for (const token of typoTokens) {
    const name = token.path.join('_').replace(/[.-]/g, '_');
    const val = token.$value as any;
    const size = parseFloat(val.fontSize) || 16;
    const weight = fontWeightToKotlin(val.fontWeight);
    const lineHeight = val.lineHeight ? `\n        lineHeight = ${parseFloat(val.lineHeight) || size * 1.5}.sp,` : '';
    kt += `    val ${name} = TextStyle(\n`;
    kt += `        fontSize = ${size}.sp,\n`;
    kt += `        fontWeight = FontWeight(${weight}),${lineHeight}\n`;
    kt += `    )\n\n`;
  }
  kt += `}\n`;

  return { path: 'DesignTypography.kt', content: kt, language: 'kotlin' };
}

function generateThemeFile(ctx: GeneratorContext, options: ComposeGeneratorOptions, pkg: string): GeneratedFile {
  const darkTheme = ctx.tokenSet.themes.themes['dark'];

  let kt = `// Auto-generated by @ryndesign/generator-compose\n`;
  kt += `package ${pkg}\n\n`;
  kt += `import androidx.compose.foundation.isSystemInDarkTheme\n`;
  kt += `import androidx.compose.runtime.Composable\n`;
  kt += `import androidx.compose.runtime.CompositionLocalProvider\n`;
  kt += `import androidx.compose.runtime.staticCompositionLocalOf\n`;
  kt += `import androidx.compose.runtime.remember\n\n`;

  kt += `val LocalDesignColors = staticCompositionLocalOf { lightDesignColors() }\n\n`;

  kt += `object DesignTheme {\n`;
  kt += `    val colors: DesignColors\n`;
  kt += `        @Composable\n`;
  kt += `        get() = LocalDesignColors.current\n`;
  kt += `}\n\n`;

  kt += `@Composable\n`;
  kt += `fun DesignTheme(\n`;
  kt += `    darkTheme: Boolean = isSystemInDarkTheme(),\n`;
  kt += `    content: @Composable () -> Unit\n`;
  kt += `) {\n`;

  if (darkTheme) {
    kt += `    val colors = remember(darkTheme) {\n`;
    kt += `        if (darkTheme) darkDesignColors() else lightDesignColors()\n`;
    kt += `    }\n`;
  } else {
    kt += `    val colors = remember { lightDesignColors() }\n`;
  }

  kt += `\n    CompositionLocalProvider(\n`;
  kt += `        LocalDesignColors provides colors,\n`;
  kt += `        content = content\n`;
  kt += `    )\n`;
  kt += `}\n`;

  return { path: 'DesignTheme.kt', content: kt, language: 'kotlin' };
}

function hexToArgbInt(hex: string): string {
  const cleaned = hex.replace('#', '');
  if (cleaned.length === 6) {
    return `0xFF${cleaned.toUpperCase()}`;
  }
  if (cleaned.length === 8) {
    // RGBA -> ARGB
    const r = cleaned.substring(0, 2);
    const g = cleaned.substring(2, 4);
    const b = cleaned.substring(4, 6);
    const a = cleaned.substring(6, 8);
    return `0x${a.toUpperCase()}${r.toUpperCase()}${g.toUpperCase()}${b.toUpperCase()}`;
  }
  return `0xFF000000`;
}

function fontWeightToKotlin(weight: number): number {
  if (weight <= 100) return 100;
  if (weight <= 200) return 200;
  if (weight <= 300) return 300;
  if (weight <= 400) return 400;
  if (weight <= 500) return 500;
  if (weight <= 600) return 600;
  if (weight <= 700) return 700;
  if (weight <= 800) return 800;
  return 900;
}
