import type { GeneratorContext, GeneratedFile, ResolvedComponent } from '@ryndesign/plugin-api';
import type { TailwindGeneratorOptions } from './index.js';

export function generateComponentFile(
  comp: ResolvedComponent,
  ctx: GeneratorContext,
  options: TailwindGeneratorOptions
): GeneratedFile[] {
  const { definition, variantTokens } = comp;
  const name = definition.name;
  const kebab = name.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();

  const content = generateClassMap(comp, options);

  return [{ path: `components/${kebab}.classes.ts`, content, language: 'typescript' }];
}

function generateClassMap(comp: ResolvedComponent, options: TailwindGeneratorOptions): string {
  const { definition, variantTokens } = comp;
  const name = definition.name;
  const prefix = options.prefix ? `${options.prefix}-` : '';
  const defaultVariant = definition.variants.variant?.default ?? 'primary';
  const defaultSize = definition.variants.size?.default ?? 'md';

  let ts = `// Auto-generated by @ryndesign/generator-tailwind\n\n`;

  // Base classes from resolved tokens
  const baseClasses: string[] = [];
  const baseTokens = variantTokens?.[defaultVariant]?.[defaultSize];
  if (baseTokens) {
    for (const [prop, token] of Object.entries(baseTokens)) {
      const twClass = tokenToTailwindClass(prop, token.path, prefix);
      if (twClass) baseClasses.push(twClass);
    }
  }

  ts += `export const ${name.toLowerCase()}Base = '${baseClasses.join(' ')}';\n\n`;

  // Variant class map
  if (definition.variants.variant) {
    ts += `export const ${name.toLowerCase()}Variant = {\n`;
    for (const variant of definition.variants.variant.values) {
      const classes: string[] = [];
      const vTokens = variantTokens?.[variant]?.[defaultSize];
      if (vTokens) {
        for (const [prop, token] of Object.entries(vTokens)) {
          if (definition.tokenMapping[prop]?.includes('{variant}')) {
            const twClass = tokenToTailwindClass(prop, token.path, prefix);
            if (twClass) classes.push(twClass);
          }
        }
      }
      ts += `  ${variant}: '${classes.join(' ')}',\n`;
    }
    ts += `} as const;\n\n`;
  }

  // Size class map
  if (definition.variants.size) {
    ts += `export const ${name.toLowerCase()}Size = {\n`;
    for (const size of definition.variants.size.values) {
      const classes: string[] = [];
      const sTokens = variantTokens?.[defaultVariant]?.[size];
      if (sTokens) {
        for (const [prop, token] of Object.entries(sTokens)) {
          if (definition.tokenMapping[prop]?.includes('{size}')) {
            const twClass = tokenToTailwindClass(prop, token.path, prefix);
            if (twClass) classes.push(twClass);
          }
        }
      }
      ts += `  ${size}: '${classes.join(' ')}',\n`;
    }
    ts += `} as const;\n\n`;
  }

  // State class map
  ts += `export const ${name.toLowerCase()}State = {\n`;
  ts += `  disabled: 'opacity-60 cursor-not-allowed pointer-events-none',\n`;
  for (const [state, stateConfig] of Object.entries(definition.states)) {
    if (state === 'disabled') continue;
    const stateClasses: string[] = [];
    for (const [prop, tokenPath] of Object.entries(stateConfig.tokenOverrides)) {
      const resolvedPath = tokenPath.replace(/\{variant\}/g, defaultVariant).replace(/\{size\}/g, defaultSize);
      const twProp = propToTailwindPrefix(prop);
      if (twProp) {
        stateClasses.push(`${state}:${twProp}-[var(--${prefix}${resolvedPath.replace(/\./g, '-')})]`);
      }
    }
    ts += `  ${state}: '${stateClasses.join(' ')}',\n`;
  }
  ts += `} as const;\n\n`;

  // Helper function
  ts += `export function get${name}Classes(\n`;
  ts += `  variant: keyof typeof ${name.toLowerCase()}Variant = '${defaultVariant}',\n`;
  ts += `  size: keyof typeof ${name.toLowerCase()}Size = '${defaultSize}',\n`;
  ts += `  disabled = false,\n`;
  ts += `): string {\n`;
  ts += `  return [\n`;
  ts += `    ${name.toLowerCase()}Base,\n`;
  ts += `    ${name.toLowerCase()}Variant[variant],\n`;
  ts += `    ${name.toLowerCase()}Size[size],\n`;
  ts += `    disabled && ${name.toLowerCase()}State.disabled,\n`;
  ts += `  ].filter(Boolean).join(' ');\n`;
  ts += `}\n`;

  return ts;
}

function tokenToTailwindClass(prop: string, path: string[], prefix: string): string | null {
  const varRef = `var(--${prefix}${path.join('-')})`;
  const twProp = propToTailwindPrefix(prop);
  if (!twProp) return null;
  return `${twProp}-[${varRef}]`;
}

function propToTailwindPrefix(prop: string): string | null {
  const map: Record<string, string> = {
    background: 'bg',
    textColor: 'text',
    borderRadius: 'rounded',
    paddingX: 'px',
    paddingY: 'py',
    fontSize: 'text',
    borderColor: 'border',
    borderWidth: 'border',
  };
  return map[prop] ?? null;
}
