import type { GeneratorContext, GeneratedFile, ResolvedToken, ResolvedValue } from '@ryndesign/plugin-api';
import type { TailwindGeneratorOptions } from './index.js';

export function generateTokenFiles(ctx: GeneratorContext, options: TailwindGeneratorOptions): GeneratedFile[] {
  const files: GeneratedFile[] = [];

  // Tailwind config with theme extension
  files.push(generateTailwindConfig(ctx, options));

  // CSS layer with custom properties (for dark mode support)
  files.push(generateCssLayer(ctx, options));

  return files;
}

function generateTailwindConfig(ctx: GeneratorContext, options: TailwindGeneratorOptions): GeneratedFile {
  const { tokens } = ctx.tokenSet;
  const prefix = options.prefix ? `${options.prefix}-` : '';
  const format = options.configFormat ?? 'ts';

  // Group tokens by category
  const colors: Record<string, string> = {};
  const spacing: Record<string, string> = {};
  const borderRadius: Record<string, string> = {};
  const fontSize: Record<string, string> = {};
  const fontWeight: Record<string, string> = {};
  const fontFamily: Record<string, string> = {};

  for (const token of tokens) {
    const key = token.path.slice(1).join('-') || token.path[0];
    const varRef = `var(--${prefix}${token.path.join('-')})`;
    const category = token.path[0];

    switch (token.$type) {
      case 'color':
        colors[key] = varRef;
        break;
      case 'dimension':
        if (category === 'spacing') {
          spacing[key] = varRef;
        } else if (category === 'borderRadius') {
          borderRadius[key] = varRef;
        } else if (category === 'fontSize') {
          fontSize[key] = varRef;
        }
        break;
      case 'fontWeight':
        fontWeight[key] = String((token.$value as { value: number }).value);
        break;
      case 'fontFamily':
        fontFamily[key] = varRef;
        break;
    }
  }

  const themeExtend = buildThemeObject({ colors, spacing, borderRadius, fontSize, fontWeight, fontFamily });

  let content: string;

  if (format === 'ts') {
    content = `// Auto-generated by @ryndesign/generator-tailwind
import type { Config } from 'tailwindcss';

export default {
  theme: {
    extend: ${themeExtend},
  },
} satisfies Partial<Config>;
`;
  } else if (format === 'cjs') {
    content = `// Auto-generated by @ryndesign/generator-tailwind
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: ${themeExtend},
  },
};
`;
  } else {
    content = `// Auto-generated by @ryndesign/generator-tailwind
/** @type {import('tailwindcss').Config} */
export default {
  theme: {
    extend: ${themeExtend},
  },
};
`;
  }

  const ext = format === 'cjs' ? '.cjs' : format === 'ts' ? '.ts' : '.js';
  return { path: `tailwind.tokens${ext}`, content, language: format === 'ts' ? 'typescript' : 'javascript' };
}

function generateCssLayer(ctx: GeneratorContext, options: TailwindGeneratorOptions): GeneratedFile {
  const { tokens, themes } = ctx.tokenSet;
  const prefix = options.prefix ? `${options.prefix}-` : '';

  let css = `/* Auto-generated by @ryndesign/generator-tailwind */\n`;
  css += `@layer base {\n`;
  css += `  :root {\n`;
  for (const token of tokens) {
    css += `    --${prefix}${token.path.join('-')}: ${resolvedValueToCss(token.$value)};\n`;
  }
  css += `  }\n\n`;

  // Dark theme
  for (const [key, theme] of Object.entries(themes.themes)) {
    if (theme.tokens.length === 0) continue;
    css += `  .${key} {\n`;
    for (const token of theme.tokens) {
      css += `    --${prefix}${token.path.join('-')}: ${resolvedValueToCss(token.$value)};\n`;
    }
    css += `  }\n\n`;

    css += `  @media (prefers-color-scheme: ${key}) {\n`;
    css += `    :root {\n`;
    for (const token of theme.tokens) {
      css += `      --${prefix}${token.path.join('-')}: ${resolvedValueToCss(token.$value)};\n`;
    }
    css += `    }\n`;
    css += `  }\n`;
  }

  css += `}\n`;

  return { path: options.cssPath ?? 'tokens.css', content: css, language: 'css' };
}

function buildThemeObject(groups: Record<string, Record<string, string>>): string {
  const lines: string[] = ['{'];

  for (const [groupName, entries] of Object.entries(groups)) {
    const keys = Object.keys(entries);
    if (keys.length === 0) continue;

    lines.push(`      ${groupName}: {`);
    for (const [key, value] of Object.entries(entries)) {
      const safeKey = key.includes('-') || key.match(/^\d/) ? `'${key}'` : key;
      lines.push(`        ${safeKey}: '${value}',`);
    }
    lines.push(`      },`);
  }

  lines.push(`    }`);
  return lines.join('\n');
}

function resolvedValueToCss(value: ResolvedValue): string {
  switch (value.type) {
    case 'color': return value.hex;
    case 'dimension': return `${value.value}${value.unit}`;
    case 'fontFamily': return value.value.join(', ');
    case 'fontWeight': return String(value.value);
    case 'duration': return `${value.value}${value.unit}`;
    case 'number': return String(value.value);
    case 'shadow': return `${value.offsetX} ${value.offsetY} ${value.blur} ${value.spread} ${value.color}`;
    case 'border': return `${value.width} ${value.style} ${value.color}`;
    default: return '';
  }
}
