import type { GeneratorContext, GeneratedFile, ResolvedComponent } from '@ryndesign/plugin-api';
import type { ReactGeneratorOptions } from './index.js';

export function generateComponentFile(
  comp: ResolvedComponent,
  ctx: GeneratorContext,
  options: ReactGeneratorOptions
): GeneratedFile[] {
  const { definition } = comp;
  const name = definition.name;
  const files: GeneratedFile[] = [];

  // Generate component TSX
  files.push({
    path: `components/${name}.tsx`,
    content: generateComponentTsx(comp, options),
    language: 'tsx',
  });

  // Generate component CSS
  files.push({
    path: `components/${name}.css`,
    content: generateComponentCss(comp),
    language: 'css',
  });

  return files;
}

function generateComponentTsx(comp: ResolvedComponent, options: ReactGeneratorOptions): string {
  const { definition } = comp;
  const name = definition.name;

  // Build props interface
  const propsLines: string[] = [];
  for (const [propName, prop] of Object.entries(definition.props)) {
    const tsType = propTypeToTs(prop.type);
    const optional = prop.required ? '' : '?';
    propsLines.push(`  ${propName}${optional}: ${tsType};`);
  }

  // Add variant props
  for (const [variantName, variant] of Object.entries(definition.variants)) {
    const unionType = variant.values.map(v => `'${v}'`).join(' | ');
    propsLines.push(`  ${variantName}?: ${unionType};`);
  }

  // Add slot props
  for (const [slotName, slot] of Object.entries(definition.slots)) {
    propsLines.push(`  ${slotName}?: React.ReactNode;`);
  }

  // Add className and style
  propsLines.push(`  className?: string;`);
  propsLines.push(`  style?: React.CSSProperties;`);

  // Build variant defaults
  const variantDefaults = Object.entries(definition.variants)
    .map(([name, v]) => `    ${name} = '${v.default}'`)
    .join(',\n');

  // Build component body
  const content = `// Auto-generated by @ryndesign/generator-react
import React from 'react';
import './${name}.css';

export interface ${name}Props {
${propsLines.join('\n')}
}

export const ${name} = React.forwardRef<HTML${getElementType(name)}Element, ${name}Props>(
  function ${name}(
    {
${variantDefaults},
      className,
      style,
      ${Object.keys(definition.props).filter(p => p !== 'onPress').join(',\n      ')},
      ${definition.props.onPress ? 'onPress,' : ''}
      ${Object.keys(definition.slots).join(',\n      ')},
      ...rest
    },
    ref
  ) {
    const classes = [
      '${kebabCase(name)}',
      \`${kebabCase(name)}--\${variant}\`,
      \`${kebabCase(name)}--\${size}\`,
      disabled && '${kebabCase(name)}--disabled',
      className,
    ].filter(Boolean).join(' ');

    return (
      <${getElementTag(name)}
        ref={ref}
        className={classes}
        style={style}
        ${definition.props.disabled ? 'disabled={disabled}' : ''}
        ${definition.props.onPress ? 'onClick={onPress}' : ''}
        {...rest}
      >
        ${Object.keys(definition.slots).includes('leadingIcon') ? '{leadingIcon && <span className="' + kebabCase(name) + '__leading-icon">{leadingIcon}</span>}' : ''}
        ${definition.props.label ? `<span className="${kebabCase(name)}__label">{label}</span>` : '{children}'}
        ${Object.keys(definition.slots).includes('trailingIcon') ? '{trailingIcon && <span className="' + kebabCase(name) + '__trailing-icon">{trailingIcon}</span>}' : ''}
      </${getElementTag(name)}>
    );
  }
);

${name}.displayName = '${name}';
export default ${name};
`;

  return content;
}

function generateComponentCss(comp: ResolvedComponent): string {
  const { definition, variantTokens } = comp;
  const base = kebabCase(definition.name);
  let css = `/* Auto-generated by @ryndesign/generator-react */\n\n`;

  const defaultVariant = definition.variants.variant?.default ?? 'primary';
  const defaultSize = definition.variants.size?.default ?? 'md';

  // Base styles using resolved variant tokens
  css += `.${base} {\n`;
  const baseTokens = variantTokens?.[defaultVariant]?.[defaultSize];
  if (baseTokens) {
    for (const [prop, token] of Object.entries(baseTokens)) {
      const cssProp = tokenMappingToCssProp(prop);
      if (cssProp) {
        css += `  ${cssProp}: var(--${token.path.join('-')});\n`;
      }
    }
  } else {
    // Fallback to tokenMapping paths for backwards compatibility
    for (const [prop, tokenPath] of Object.entries(definition.tokenMapping)) {
      const cssProp = tokenMappingToCssProp(prop);
      if (cssProp) {
        const resolvedPath = tokenPath
          .replace('{variant}', defaultVariant)
          .replace('{size}', defaultSize);
        css += `  ${cssProp}: var(--${resolvedPath.replace(/\./g, '-')});\n`;
      }
    }
  }
  css += `  cursor: pointer;\n`;
  css += `  border: none;\n`;
  css += `  display: inline-flex;\n`;
  css += `  align-items: center;\n`;
  css += `  justify-content: center;\n`;
  css += `  gap: 8px;\n`;
  css += `  transition: background-color 150ms ease, color 150ms ease;\n`;
  css += '}\n\n';

  // Variant styles using variantTokens
  if (definition.variants.variant) {
    for (const variant of definition.variants.variant.values) {
      css += `.${base}--${variant} {\n`;
      const vTokens = variantTokens?.[variant]?.[defaultSize];
      if (vTokens) {
        for (const [prop, token] of Object.entries(vTokens)) {
          if (definition.tokenMapping[prop]?.includes('{variant}')) {
            const cssProp = tokenMappingToCssProp(prop);
            if (cssProp) {
              css += `  ${cssProp}: var(--${token.path.join('-')});\n`;
            }
          }
        }
      } else {
        for (const [prop, tokenPath] of Object.entries(definition.tokenMapping)) {
          if (tokenPath.includes('{variant}')) {
            const cssProp = tokenMappingToCssProp(prop);
            if (cssProp) {
              const resolvedPath = tokenPath.replace('{variant}', variant).replace('{size}', defaultSize);
              css += `  ${cssProp}: var(--${resolvedPath.replace(/\./g, '-')});\n`;
            }
          }
        }
      }
      css += '}\n\n';
    }
  }

  // Size styles using variantTokens
  if (definition.variants.size) {
    for (const size of definition.variants.size.values) {
      css += `.${base}--${size} {\n`;
      const sTokens = variantTokens?.[defaultVariant]?.[size];
      if (sTokens) {
        for (const [prop, token] of Object.entries(sTokens)) {
          if (definition.tokenMapping[prop]?.includes('{size}')) {
            const cssProp = tokenMappingToCssProp(prop);
            if (cssProp) {
              css += `  ${cssProp}: var(--${token.path.join('-')});\n`;
            }
          }
        }
      } else {
        for (const [prop, tokenPath] of Object.entries(definition.tokenMapping)) {
          if (tokenPath.includes('{size}')) {
            const cssProp = tokenMappingToCssProp(prop);
            if (cssProp) {
              const resolvedPath = tokenPath.replace('{size}', size).replace('{variant}', defaultVariant);
              css += `  ${cssProp}: var(--${resolvedPath.replace(/\./g, '-')});\n`;
            }
          }
        }
      }
      css += '}\n\n';
    }
  }

  // State styles
  for (const [state, stateConfig] of Object.entries(definition.states)) {
    const pseudo = stateToCssPseudo(state);
    for (const [prop, tokenPath] of Object.entries(stateConfig.tokenOverrides)) {
      const cssProp = tokenMappingToCssProp(prop);
      if (cssProp) {
        if (state === 'disabled') {
          css += `.${base}--disabled {\n`;
          const resolvedPath = tokenPath.replace(/\{variant\}/g, defaultVariant);
          css += `  ${cssProp}: var(--${resolvedPath.replace(/\./g, '-')});\n`;
          css += `  cursor: not-allowed;\n`;
          css += `  opacity: 0.6;\n`;
          css += '}\n\n';
        } else {
          // For each variant
          if (definition.variants.variant) {
            for (const variant of definition.variants.variant.values) {
              css += `.${base}--${variant}${pseudo} {\n`;
              const resolvedPath = tokenPath.replace('{variant}', variant);
              css += `  ${cssProp}: var(--${resolvedPath.replace(/\./g, '-')});\n`;
              css += '}\n\n';
            }
          }
        }
      }
    }
  }

  return css;
}

function tokenMappingToCssProp(mapping: string): string | null {
  const map: Record<string, string> = {
    background: 'background-color',
    textColor: 'color',
    borderRadius: 'border-radius',
    paddingX: 'padding-inline',
    paddingY: 'padding-block',
    fontSize: 'font-size',
    borderColor: 'border-color',
    borderWidth: 'border-width',
  };
  return map[mapping] ?? null;
}

function stateToCssPseudo(state: string): string {
  const map: Record<string, string> = {
    hover: ':hover:not(:disabled)',
    pressed: ':active:not(:disabled)',
    focus: ':focus-visible',
    disabled: ':disabled',
  };
  return map[state] ?? `:${state}`;
}

function propTypeToTs(type: string): string {
  const map: Record<string, string> = {
    string: 'string',
    boolean: 'boolean',
    number: 'number',
    callback: '() => void',
    node: 'React.ReactNode',
  };
  return map[type] ?? 'unknown';
}

function getElementType(name: string): string {
  const map: Record<string, string> = {
    Button: 'Button',
    Input: 'Input',
    Card: 'Div',
    Checkbox: 'Input',
    Toggle: 'Button',
    Badge: 'Span',
    Avatar: 'Div',
  };
  return map[name] ?? 'Div';
}

function getElementTag(name: string): string {
  const map: Record<string, string> = {
    Button: 'button',
    Input: 'input',
    Card: 'div',
    Checkbox: 'label',
    Toggle: 'button',
    Badge: 'span',
    Avatar: 'div',
  };
  return map[name] ?? 'div';
}

function kebabCase(str: string): string {
  return str.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();
}
