import type { GeneratorContext, GeneratedFile, ResolvedToken, ResolvedValue } from '@ryndesign/plugin-api';
import type { ReactGeneratorOptions } from './index.js';

export function generateTokenFiles(ctx: GeneratorContext, options: ReactGeneratorOptions): GeneratedFile[] {
  const files: GeneratedFile[] = [];

  // 1. CSS custom properties file
  files.push(generateCssFile(ctx, options));

  // 2. TypeScript token constants
  if (options.typescript !== false) {
    files.push(generateTsTokens(ctx));
  }

  // 3. Theme provider
  files.push(generateThemeProvider(ctx, options));

  return files;
}

function generateCssFile(ctx: GeneratorContext, options: ReactGeneratorOptions): GeneratedFile {
  const { tokens, themes } = ctx.tokenSet;
  let css = '';

  // Root (light/default) tokens
  css += ':root {\n';
  for (const token of tokens) {
    const varName = tokenToCssVar(token.path);
    const value = resolvedValueToCss(token.$value);
    css += `  ${varName}: ${value};\n`;
  }
  css += '}\n\n';

  // Dark mode tokens
  for (const [key, theme] of Object.entries(themes.themes)) {
    if (theme.tokens.length === 0) continue;

    const selectors: string[] = [];

    if (options.darkMode === 'media' || options.darkMode === 'media+class') {
      // Generate media query version
      css += `@media (prefers-color-scheme: ${key}) {\n`;
      css += '  :root {\n';
      for (const token of theme.tokens) {
        const varName = tokenToCssVar(token.path);
        const value = resolvedValueToCss(token.$value);
        css += `    ${varName}: ${value};\n`;
      }
      css += '  }\n';
      css += '}\n\n';
    }

    if (options.darkMode === 'class' || options.darkMode === 'media+class') {
      // Generate class/data-attribute version
      css += `[data-theme="${key}"] {\n`;
      for (const token of theme.tokens) {
        const varName = tokenToCssVar(token.path);
        const value = resolvedValueToCss(token.$value);
        css += `  ${varName}: ${value};\n`;
      }
      css += '}\n\n';
    }

    if (!options.darkMode || options.darkMode === 'media+class') {
      // Default: both strategies
      if (options.darkMode !== 'media+class') {
        css += `@media (prefers-color-scheme: ${key}) {\n`;
        css += '  :root {\n';
        for (const token of theme.tokens) {
          const varName = tokenToCssVar(token.path);
          const value = resolvedValueToCss(token.$value);
          css += `    ${varName}: ${value};\n`;
        }
        css += '  }\n';
        css += '}\n\n';

        css += `[data-theme="${key}"] {\n`;
        for (const token of theme.tokens) {
          const varName = tokenToCssVar(token.path);
          const value = resolvedValueToCss(token.$value);
          css += `  ${varName}: ${value};\n`;
        }
        css += '}\n\n';
      }
    }
  }

  return {
    path: 'tokens.css',
    content: css,
    language: 'css',
  };
}

function generateTsTokens(ctx: GeneratorContext): GeneratedFile {
  const { tokens } = ctx.tokenSet;
  let ts = '// Auto-generated by @ryndesign/generator-react\n';
  ts += '// Do not edit manually\n\n';

  ts += 'export const tokens = {\n';
  const grouped = groupByFirstPath(tokens);

  for (const [group, groupTokens] of Object.entries(grouped)) {
    ts += `  ${group}: {\n`;
    for (const token of groupTokens) {
      const key = token.path.slice(1).join('_').replace(/[.-]/g, '_');
      const varName = tokenToCssVar(token.path);
      ts += `    ${key}: 'var(${varName})',\n`;
    }
    ts += '  },\n';
  }
  ts += '} as const;\n\n';

  ts += 'export type TokenPath = keyof typeof tokens;\n';

  return {
    path: 'tokens.ts',
    content: ts,
    language: 'typescript',
  };
}

function generateThemeProvider(ctx: GeneratorContext, options: ReactGeneratorOptions): GeneratedFile {
  const themeNames = ['light', ...Object.keys(ctx.tokenSet.themes.themes)];

  const content = `// Auto-generated by @ryndesign/generator-react
import React, { createContext, useContext, useState, useEffect, type ReactNode } from 'react';

export type Theme = ${themeNames.map(t => `'${t}'`).join(' | ')};

interface ThemeContextValue {
  theme: Theme;
  setTheme: (theme: Theme) => void;
  toggleTheme: () => void;
}

const ThemeContext = createContext<ThemeContextValue | undefined>(undefined);

interface ThemeProviderProps {
  defaultTheme?: Theme;
  children: ReactNode;
}

export function ThemeProvider({ defaultTheme = '${ctx.tokenSet.themes.default}', children }: ThemeProviderProps) {
  const [theme, setTheme] = useState<Theme>(defaultTheme);

  useEffect(() => {
    document.documentElement.setAttribute('data-theme', theme === 'light' ? '' : theme);
  }, [theme]);

  const toggleTheme = () => {
    setTheme(prev => prev === 'light' ? 'dark' : 'light');
  };

  return (
    <ThemeContext.Provider value={{ theme, setTheme, toggleTheme }}>
      {children}
    </ThemeContext.Provider>
  );
}

export function useTheme(): ThemeContextValue {
  const ctx = useContext(ThemeContext);
  if (!ctx) throw new Error('useTheme must be used within a ThemeProvider');
  return ctx;
}
`;

  return {
    path: 'ThemeProvider.tsx',
    content,
    language: 'tsx',
  };
}

function tokenToCssVar(path: string[]): string {
  return `--${path.join('-').replace(/\./g, '-')}`;
}

function resolvedValueToCss(value: ResolvedValue): string {
  switch (value.type) {
    case 'color':
      return value.hex;
    case 'dimension':
      return `${value.value}${value.unit}`;
    case 'fontFamily':
      return value.value.join(', ');
    case 'fontWeight':
      return String(value.value);
    case 'duration':
      return `${value.value}${value.unit}`;
    case 'cubicBezier':
      return `cubic-bezier(${value.value.join(', ')})`;
    case 'number':
      return String(value.value);
    case 'shadow':
      return `${value.offsetX} ${value.offsetY} ${value.blur} ${value.spread} ${value.color}`;
    case 'border':
      return `${value.width} ${value.style} ${value.color}`;
    case 'typography':
      return `${value.fontWeight} ${value.fontSize}/${value.lineHeight} ${value.fontFamily}`;
    case 'transition':
      return `${value.duration} ${value.timingFunction} ${value.delay}`;
    case 'gradient':
      if (value.gradientType === 'linear') {
        const stops = value.stops.map(s => `${s.color} ${s.position * 100}%`).join(', ');
        return `linear-gradient(${value.angle ?? 0}deg, ${stops})`;
      }
      return 'none';
    default:
      return '';
  }
}

function groupByFirstPath(tokens: ResolvedToken[]): Record<string, ResolvedToken[]> {
  const groups: Record<string, ResolvedToken[]> = {};
  for (const token of tokens) {
    const key = token.path[0];
    if (!groups[key]) groups[key] = [];
    groups[key].push(token);
  }
  return groups;
}
