import { describe, it, expect } from 'vitest';
import { railsGenerator } from '../index.js';
import { buildTokenSet } from '@ryndesign/core';
import path from 'node:path';

const TEMPLATES_DIR = path.resolve(__dirname, '../../../../templates');

async function getTestContext() {
  const tokenSet = await buildTokenSet({
    tokens: ['minimal.tokens.json'],
    basePath: TEMPLATES_DIR,
    themes: {
      default: 'light',
      dark: { file: path.join(TEMPLATES_DIR, 'dark.tokens.json') },
    },
  });

  return {
    tokenSet,
    config: { outDir: 'generated/rails', darkMode: 'media+class' as const },
    outputDir: '/tmp/test-output',
    helpers: {
      camelCase: (s: string) => s.replace(/[-_](\w)/g, (_, c) => c.toUpperCase()),
      pascalCase: (s: string) => s.replace(/(^|[-_])(\w)/g, (_, __, c) => c.toUpperCase()),
      kebabCase: (s: string) => s.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase(),
      snakeCase: (s: string) => s.replace(/([a-z])([A-Z])/g, '$1_$2').toLowerCase(),
      tokenToCssVar: (p: string[]) => `--${p.join('-')}`,
      tokenToScssVar: (p: string[]) => `$${p.join('-')}`,
      formatColor: (hex: string) => hex,
    },
  };
}

describe('Rails Generator', () => {
  it('should create a generator plugin with correct metadata', () => {
    const gen = railsGenerator();
    expect(gen.name).toBe('rails');
    expect(gen.displayName).toBe('Rails');
    expect(gen.platform).toBe('web');
    expect(gen.outputExtensions).toContain('.scss');
    expect(gen.outputExtensions).toContain('.erb');
    expect(gen.outputExtensions).toContain('.rb');
  });

  it('should generate SCSS variables file', async () => {
    const gen = railsGenerator({ darkMode: 'media+class' });
    const ctx = await getTestContext();
    const files = await gen.generateTokens(ctx);

    const scssFile = files.find(f => f.path === '_tokens.scss');
    expect(scssFile).toBeDefined();
    expect(scssFile!.content).toContain('$color-primary');
    expect(scssFile!.content).toContain('#3B82F6');
    expect(scssFile!.content).toContain('$spacing-xs');
    expect(scssFile!.content).toContain('4px');
    expect(scssFile!.content).toContain('Auto-generated by @ryndesign/generator-rails');
  });

  it('should generate CSS custom properties file', async () => {
    const gen = railsGenerator({ darkMode: 'media+class' });
    const ctx = await getTestContext();
    const files = await gen.generateTokens(ctx);

    const cssFile = files.find(f => f.path === '_tokens-custom-properties.scss');
    expect(cssFile).toBeDefined();
    expect(cssFile!.content).toContain(':root');
    expect(cssFile!.content).toContain('--color-primary');
    expect(cssFile!.content).toContain('#3B82F6');
  });

  it('should include dark theme SCSS variable overrides', async () => {
    const gen = railsGenerator({ darkMode: 'media+class' });
    const ctx = await getTestContext();
    const files = await gen.generateTokens(ctx);

    const scssFile = files.find(f => f.path === '_tokens.scss')!;
    expect(scssFile.content).toContain('Dark theme overrides');
    expect(scssFile.content).toContain('--dark');
  });

  it('should include dark mode CSS with media query and class selector', async () => {
    const gen = railsGenerator({ darkMode: 'media+class' });
    const ctx = await getTestContext();
    const files = await gen.generateTokens(ctx);

    const cssFile = files.find(f => f.path === '_tokens-custom-properties.scss')!;
    expect(cssFile.content).toContain('prefers-color-scheme');
    expect(cssFile.content).toContain('.theme-dark');
  });

  it('should produce exactly 2 files', async () => {
    const gen = railsGenerator();
    const ctx = await getTestContext();
    const files = await gen.generateTokens(ctx);

    expect(files.length).toBe(2);
    expect(files.map(f => f.path)).toContain('_tokens.scss');
    expect(files.map(f => f.path)).toContain('_tokens-custom-properties.scss');
  });
});
