import type { GeneratorContext, GeneratedFile, ResolvedComponent } from '@ryndesign/plugin-api';
import type { SvelteGeneratorOptions } from './index.js';

export function generateComponentFile(comp: ResolvedComponent, ctx: GeneratorContext, options: SvelteGeneratorOptions): GeneratedFile[] {
  const { definition } = comp;
  const name = definition.name;
  const kebab = name.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();

  const propsDeclarations = Object.entries(definition.props)
    .map(([k, v]) => {
      const tsType = propTypeToTs(v.type);
      if (v.required) {
        return `  export let ${k}: ${tsType};`;
      }
      return `  export let ${k}: ${tsType} = ${getDefaultValue(v.type)};`;
    })
    .join('\n');

  const variantDeclarations = Object.entries(definition.variants)
    .map(([k, v]) => {
      const unionType = v.values.map((val: string) => `'${val}'`).join(' | ');
      return `  export let ${k}: ${unionType} = '${v.default}';`;
    })
    .join('\n');

  const content = `<!-- Auto-generated by @ryndesign/generator-svelte -->
<script lang="ts">
${propsDeclarations}
${variantDeclarations}
  export let disabled: boolean = false;

  $: classes = \`${kebab} ${kebab}--\${variant} ${kebab}--\${size} \${disabled ? '${kebab}--disabled' : ''}\`.trim();
</script>

<${getElementTag(name)} class={classes} {disabled} on:click>
  <slot name="leadingIcon" />
  <span class="${kebab}__label">{label}</span>
  <slot name="trailingIcon" />
</${getElementTag(name)}>

<style>
${generateComponentCss(comp, kebab)}
</style>
`;

  return [{ path: `components/${name}.svelte`, content, language: 'svelte' }];
}

function generateComponentCss(comp: ResolvedComponent, base: string): string {
  const { definition, variantTokens } = comp;
  const defaultVariant = definition.variants.variant?.default ?? 'primary';
  const defaultSize = definition.variants.size?.default ?? 'md';

  let css = '';

  // Base styles
  css += `  .${base} {\n`;
  const baseTokens = variantTokens?.[defaultVariant]?.[defaultSize];
  if (baseTokens) {
    for (const [prop, token] of Object.entries(baseTokens)) {
      const cssProp = tokenMappingToCssProp(prop);
      if (cssProp) {
        css += `    ${cssProp}: var(--${token.path.join('-')});\n`;
      }
    }
  } else {
    for (const [prop, path] of Object.entries(definition.tokenMapping)) {
      const cssProp = tokenMappingToCssProp(prop);
      if (!cssProp) continue;
      const resolved = (path as string)
        .replace('{variant}', defaultVariant)
        .replace('{size}', defaultSize);
      css += `    ${cssProp}: var(--${resolved.replace(/\./g, '-')});\n`;
    }
  }
  css += `    cursor: pointer;\n`;
  css += `    border: none;\n`;
  css += `    display: inline-flex;\n`;
  css += `    align-items: center;\n`;
  css += `    gap: 8px;\n`;
  css += `    transition: background-color 150ms ease, color 150ms ease;\n`;
  css += `  }\n\n`;

  // Variant styles
  if (definition.variants.variant) {
    for (const variant of definition.variants.variant.values) {
      css += `  .${base}--${variant} {\n`;
      const vTokens = variantTokens?.[variant]?.[defaultSize];
      if (vTokens) {
        for (const [prop, token] of Object.entries(vTokens)) {
          if (definition.tokenMapping[prop]?.includes('{variant}')) {
            const cssProp = tokenMappingToCssProp(prop);
            if (cssProp) {
              css += `    ${cssProp}: var(--${token.path.join('-')});\n`;
            }
          }
        }
      } else {
        for (const [prop, tokenPath] of Object.entries(definition.tokenMapping)) {
          if (tokenPath.includes('{variant}')) {
            const cssProp = tokenMappingToCssProp(prop);
            if (cssProp) {
              const resolvedPath = tokenPath.replace('{variant}', variant).replace('{size}', defaultSize);
              css += `    ${cssProp}: var(--${resolvedPath.replace(/\./g, '-')});\n`;
            }
          }
        }
      }
      css += `  }\n\n`;
    }
  }

  // Size styles
  if (definition.variants.size) {
    for (const size of definition.variants.size.values) {
      css += `  .${base}--${size} {\n`;
      const sTokens = variantTokens?.[defaultVariant]?.[size];
      if (sTokens) {
        for (const [prop, token] of Object.entries(sTokens)) {
          if (definition.tokenMapping[prop]?.includes('{size}')) {
            const cssProp = tokenMappingToCssProp(prop);
            if (cssProp) {
              css += `    ${cssProp}: var(--${token.path.join('-')});\n`;
            }
          }
        }
      } else {
        for (const [prop, tokenPath] of Object.entries(definition.tokenMapping)) {
          if (tokenPath.includes('{size}')) {
            const cssProp = tokenMappingToCssProp(prop);
            if (cssProp) {
              const resolvedPath = tokenPath.replace('{size}', size).replace('{variant}', defaultVariant);
              css += `    ${cssProp}: var(--${resolvedPath.replace(/\./g, '-')});\n`;
            }
          }
        }
      }
      css += `  }\n\n`;
    }
  }

  // State styles
  for (const [state, stateConfig] of Object.entries(definition.states)) {
    for (const [prop, tokenPath] of Object.entries(stateConfig.tokenOverrides)) {
      const cssProp = tokenMappingToCssProp(prop);
      if (!cssProp) continue;
      if (state === 'disabled') {
        css += `  .${base}--disabled {\n`;
        const resolvedPath = tokenPath.replace(/\{variant\}/g, defaultVariant);
        css += `    ${cssProp}: var(--${resolvedPath.replace(/\./g, '-')});\n`;
        css += `    cursor: not-allowed;\n`;
        css += `    opacity: 0.6;\n`;
        css += `  }\n\n`;
      } else {
        const pseudo = state === 'hover' ? ':hover:not(:disabled)' : state === 'pressed' ? ':active:not(:disabled)' : `:${state}`;
        if (definition.variants.variant) {
          for (const variant of definition.variants.variant.values) {
            css += `  .${base}--${variant}${pseudo} {\n`;
            const resolvedPath = tokenPath.replace('{variant}', variant);
            css += `    ${cssProp}: var(--${resolvedPath.replace(/\./g, '-')});\n`;
            css += `  }\n\n`;
          }
        }
      }
    }
  }

  return css.trimEnd();
}

function propTypeToTs(type: string): string {
  return { string: 'string', boolean: 'boolean', number: 'number', callback: '() => void', node: 'any' }[type] ?? 'unknown';
}

function getDefaultValue(type: string): string {
  return { string: "''", boolean: 'false', number: '0', callback: '() => {}', node: 'undefined' }[type] ?? 'undefined';
}

function getElementTag(name: string): string {
  return { Button: 'button', Input: 'input', Card: 'div', Checkbox: 'label', Toggle: 'button', Badge: 'span', Avatar: 'div' }[name] ?? 'div';
}

function tokenMappingToCssProp(mapping: string): string | null {
  return { background: 'background-color', textColor: 'color', borderRadius: 'border-radius', paddingX: 'padding-inline', paddingY: 'padding-block', fontSize: 'font-size', borderColor: 'border-color' }[mapping] ?? null;
}
