import type { GeneratorContext, GeneratedFile, ResolvedComponent } from '@ryndesign/plugin-api';
import type { SvelteGeneratorOptions } from './index.js';

export function generateComponentFile(comp: ResolvedComponent, ctx: GeneratorContext, options: SvelteGeneratorOptions): GeneratedFile[] {
  const { definition } = comp;
  const name = definition.name;
  const kebab = name.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();

  const propsDeclarations = Object.entries(definition.props)
    .map(([k, v]) => {
      const tsType = propTypeToTs(v.type);
      if (v.required) {
        return `  export let ${k}: ${tsType};`;
      }
      return `  export let ${k}: ${tsType} = ${getDefaultValue(v.type)};`;
    })
    .join('\n');

  const variantDeclarations = Object.entries(definition.variants)
    .map(([k, v]) => {
      const unionType = v.values.map((val: string) => `'${val}'`).join(' | ');
      return `  export let ${k}: ${unionType} = '${v.default}';`;
    })
    .join('\n');

  const tokenStyles = Object.entries(definition.tokenMapping)
    .map(([prop, path]) => {
      const cssProp = tokenMappingToCssProp(prop);
      if (!cssProp) return '';
      const resolved = (path as string)
        .replace('{variant}', definition.variants.variant?.default ?? 'primary')
        .replace('{size}', definition.variants.size?.default ?? 'md');
      return `  ${cssProp}: var(--${resolved.replace(/\./g, '-')});`;
    })
    .filter(Boolean)
    .join('\n');

  const content = `<!-- Auto-generated by @ryndesign/generator-svelte -->
<script lang="ts">
${propsDeclarations}
${variantDeclarations}
  export let disabled: boolean = false;

  $: classes = \`${kebab} ${kebab}--\${variant} ${kebab}--\${size} \${disabled ? '${kebab}--disabled' : ''}\`.trim();
</script>

<${getElementTag(name)} class={classes} {disabled} on:click>
  <slot name="leadingIcon" />
  <span class="${kebab}__label">{label}</span>
  <slot name="trailingIcon" />
</${getElementTag(name)}>

<style>
  .${kebab} {
${tokenStyles}
    cursor: pointer;
    border: none;
    display: inline-flex;
    align-items: center;
    gap: 8px;
  }
</style>
`;

  return [{ path: `components/${name}.svelte`, content, language: 'svelte' }];
}

function propTypeToTs(type: string): string {
  return { string: 'string', boolean: 'boolean', number: 'number', callback: '() => void', node: 'any' }[type] ?? 'unknown';
}

function getDefaultValue(type: string): string {
  return { string: "''", boolean: 'false', number: '0', callback: '() => {}', node: 'undefined' }[type] ?? 'undefined';
}

function getElementTag(name: string): string {
  return { Button: 'button', Input: 'input', Card: 'div', Checkbox: 'label', Toggle: 'button', Badge: 'span', Avatar: 'div' }[name] ?? 'div';
}

function tokenMappingToCssProp(mapping: string): string | null {
  return { background: 'background-color', textColor: 'color', borderRadius: 'border-radius', paddingX: 'padding-inline', paddingY: 'padding-block', fontSize: 'font-size' }[mapping] ?? null;
}
