import type { GeneratorContext, GeneratedFile, ResolvedToken, ResolvedValue } from '@ryndesign/plugin-api';
import type { SvelteGeneratorOptions } from './index.js';

export function generateTokenFiles(ctx: GeneratorContext, options: SvelteGeneratorOptions): GeneratedFile[] {
  const files: GeneratedFile[] = [];

  // CSS custom properties
  files.push(generateCssFile(ctx, options));

  // TypeScript token constants
  if (options.typescript !== false) {
    files.push(generateTsTokens(ctx));
  }

  // Svelte theme store
  files.push(generateThemeStore(ctx));

  return files;
}

function generateCssFile(ctx: GeneratorContext, options: SvelteGeneratorOptions): GeneratedFile {
  const { tokens, themes } = ctx.tokenSet;
  let css = ':root {\n';
  for (const token of tokens) {
    css += `  --${token.path.join('-')}: ${resolvedValueToCss(token.$value)};\n`;
  }
  css += '}\n\n';

  for (const [key, theme] of Object.entries(themes.themes)) {
    if (theme.tokens.length === 0) continue;
    if (options.darkMode !== 'class') {
      css += `@media (prefers-color-scheme: ${key}) {\n  :root {\n`;
      for (const token of theme.tokens) {
        css += `    --${token.path.join('-')}: ${resolvedValueToCss(token.$value)};\n`;
      }
      css += '  }\n}\n\n';
    }
    if (options.darkMode !== 'media') {
      css += `[data-theme="${key}"] {\n`;
      for (const token of theme.tokens) {
        css += `  --${token.path.join('-')}: ${resolvedValueToCss(token.$value)};\n`;
      }
      css += '}\n\n';
    }
  }

  return { path: 'tokens.css', content: css, language: 'css' };
}

function generateTsTokens(ctx: GeneratorContext): GeneratedFile {
  let ts = '// Auto-generated by @ryndesign/generator-svelte\nexport const tokens = {\n';
  for (const token of ctx.tokenSet.tokens) {
    const key = token.path.join('_').replace(/[.-]/g, '_');
    ts += `  '${key}': 'var(--${token.path.join('-')})',\n`;
  }
  ts += '} as const;\n';
  return { path: 'tokens.ts', content: ts, language: 'typescript' };
}

function generateThemeStore(ctx: GeneratorContext): GeneratedFile {
  const themes = ['light', ...Object.keys(ctx.tokenSet.themes.themes)];
  const content = `// Auto-generated by @ryndesign/generator-svelte
import { writable } from 'svelte/store';

export type Theme = ${themes.map(t => `'${t}'`).join(' | ')};

export const theme = writable<Theme>('${ctx.tokenSet.themes.default}');

theme.subscribe(value => {
  if (typeof document !== 'undefined') {
    document.documentElement.setAttribute('data-theme', value === 'light' ? '' : value);
  }
});

export function setTheme(value: Theme) {
  theme.set(value);
}

export function toggleTheme() {
  theme.update(t => t === 'light' ? 'dark' : 'light');
}
`;
  return { path: 'themeStore.ts', content, language: 'typescript' };
}

function resolvedValueToCss(value: ResolvedValue): string {
  switch (value.type) {
    case 'color': return value.hex;
    case 'dimension': return `${value.value}${value.unit}`;
    case 'fontFamily': return value.value.join(', ');
    case 'fontWeight': return String(value.value);
    case 'duration': return `${value.value}${value.unit}`;
    case 'number': return String(value.value);
    case 'shadow': return `${value.offsetX} ${value.offsetY} ${value.blur} ${value.spread} ${value.color}`;
    case 'border': return `${value.width} ${value.style} ${value.color}`;
    default: return '';
  }
}
