import { describe, it, expect } from 'vitest';
import { androidViewGenerator } from '../index.js';
import { buildTokenSet } from '@ryndesign/core';
import path from 'node:path';

const TEMPLATES_DIR = path.resolve(__dirname, '../../../../templates');

async function getTestContext() {
  const tokenSet = await buildTokenSet({
    tokens: ['minimal.tokens.json'],
    basePath: TEMPLATES_DIR,
    themes: {
      default: 'light',
      dark: { file: path.join(TEMPLATES_DIR, 'dark.tokens.json') },
    },
  });

  return {
    tokenSet,
    config: { outDir: 'generated/android-view' },
    outputDir: '/tmp/test-output',
    helpers: {
      camelCase: (s: string) => s.replace(/[-_](\w)/g, (_, c) => c.toUpperCase()),
      pascalCase: (s: string) => s.replace(/(^|[-_])(\w)/g, (_, __, c) => c.toUpperCase()),
      kebabCase: (s: string) => s.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase(),
      snakeCase: (s: string) => s.replace(/([a-z])([A-Z])/g, '$1_$2').toLowerCase(),
      tokenToCssVar: (p: string[]) => `--${p.join('-')}`,
      tokenToScssVar: (p: string[]) => `$${p.join('-')}`,
      formatColor: (hex: string) => hex,
    },
  };
}

describe('Android View Generator', () => {
  it('should create a generator plugin with correct metadata', () => {
    const gen = androidViewGenerator();
    expect(gen.name).toBe('android-view');
    expect(gen.displayName).toBe('Android View');
    expect(gen.platform).toBe('android');
    expect(gen.outputExtensions).toContain('.kt');
    expect(gen.outputExtensions).toContain('.xml');
  });

  it('should generate colors.xml, values-night/colors.xml, dimens.xml, typography, and attrs', async () => {
    const gen = androidViewGenerator();
    const ctx = await getTestContext();
    const files = await gen.generateTokens(ctx);

    expect(files.length).toBe(5);

    const colorsFile = files.find(f => f.path === 'values/colors.xml');
    expect(colorsFile).toBeDefined();
    expect(colorsFile!.content).toContain('<resources>');
    expect(colorsFile!.content).toContain('<color name=');

    const nightColorsFile = files.find(f => f.path === 'values-night/colors.xml');
    expect(nightColorsFile).toBeDefined();
    expect(nightColorsFile!.content).toContain('<resources>');

    const dimensFile = files.find(f => f.path === 'values/dimens.xml');
    expect(dimensFile).toBeDefined();
    expect(dimensFile!.content).toContain('<dimen name=');
  });

  it('should generate correct color values in colors.xml', async () => {
    const gen = androidViewGenerator();
    const ctx = await getTestContext();
    const files = await gen.generateTokens(ctx);
    const colorsFile = files.find(f => f.path === 'values/colors.xml')!;

    expect(colorsFile.content).toContain('color_primary');
    expect(colorsFile.content).toContain('#3B82F6');
    expect(colorsFile.content).toContain('<?xml version="1.0"');
    expect(colorsFile.content).toContain('Auto-generated by @ryndesign/generator-android-view');
  });

  it('should generate night colors with dark theme overrides', async () => {
    const gen = androidViewGenerator();
    const ctx = await getTestContext();
    const files = await gen.generateTokens(ctx);
    const nightFile = files.find(f => f.path === 'values-night/colors.xml')!;

    // Dark theme overrides color.background.primary to gray.900 (#111827)
    expect(nightFile.content).toContain('color_background_primary');
    expect(nightFile.content).toContain('#111827');
  });

  it('should generate dimens.xml with dp units', async () => {
    const gen = androidViewGenerator();
    const ctx = await getTestContext();
    const files = await gen.generateTokens(ctx);
    const dimensFile = files.find(f => f.path === 'values/dimens.xml')!;

    expect(dimensFile.content).toContain('spacing_xs');
    expect(dimensFile.content).toContain('4dp');
    expect(dimensFile.content).toContain('spacing_md');
    expect(dimensFile.content).toContain('16dp');
  });

  it('should generate theme attrs with declare-styleable', async () => {
    const gen = androidViewGenerator();
    const ctx = await getTestContext();
    const files = await gen.generateTokens(ctx);
    const attrsFile = files.find(f => f.path === 'values/attrs_design.xml')!;

    expect(attrsFile.content).toContain('declare-styleable');
    expect(attrsFile.content).toContain('DesignTokens');
    expect(attrsFile.content).toContain('design_color_primary');
    expect(attrsFile.content).toContain('format="color"');
    expect(attrsFile.content).toContain('Theme.Design.Overlay');
    expect(attrsFile.content).toContain('@color/color_primary');
  });

  it('should generate typography styles XML', async () => {
    const gen = androidViewGenerator();
    const ctx = await getTestContext();
    const files = await gen.generateTokens(ctx);
    const typoFile = files.find(f => f.path === 'values/typography_styles.xml')!;

    // minimal.tokens.json doesn't have typography tokens, so it should
    // still generate a valid XML structure
    expect(typoFile.content).toContain('<?xml version="1.0"');
    expect(typoFile.content).toContain('<resources>');
    expect(typoFile.content).toContain('</resources>');
  });
});
