import type { GeneratorContext, GeneratedFile, ResolvedComponent } from '@ryndesign/plugin-api';
import type { SwiftUIGeneratorOptions } from './index.js';

export function generateComponentFile(
  comp: ResolvedComponent,
  ctx: GeneratorContext,
  options: SwiftUIGeneratorOptions
): GeneratedFile[] {
  const { definition } = comp;
  const name = `DS${definition.name}`;
  const files: GeneratedFile[] = [];

  files.push({
    path: `components/${name}.swift`,
    content: generateSwiftUIView(comp, options),
    language: 'swift',
  });

  return files;
}

function generateSwiftUIView(comp: ResolvedComponent, options: SwiftUIGeneratorOptions): string {
  const { definition } = comp;
  const name = `DS${definition.name}`;

  let swift = `// Auto-generated by @ryndesign/generator-swiftui\nimport SwiftUI\n\n`;

  // Generate the View struct
  swift += `struct ${name}: View {\n`;

  // Properties from component props
  for (const [propName, prop] of Object.entries(definition.props)) {
    const swiftType = propTypeToSwift(prop.type);
    if (prop.type === 'callback') {
      swift += `    var ${propName}: (() -> Void)?\n`;
    } else if (prop.required) {
      swift += `    let ${propName}: ${swiftType}\n`;
    } else {
      const defaultVal = swiftDefaultValue(prop.type, prop.default);
      swift += `    var ${propName}: ${swiftType} = ${defaultVal}\n`;
    }
  }

  // Variant enums and properties
  for (const [variantName, variant] of Object.entries(definition.variants)) {
    const enumName = capitalize(variantName);
    swift += `    var ${variantName}: ${enumName} = .${variant.default}\n`;
  }

  swift += `\n`;

  // Generate variant enums
  for (const [variantName, variant] of Object.entries(definition.variants)) {
    const enumName = capitalize(variantName);
    swift += `    enum ${enumName}: String, CaseIterable {\n`;
    for (const value of variant.values) {
      swift += `        case ${value}\n`;
    }
    swift += `    }\n\n`;
  }

  // Generate computed properties for token-based styling
  swift += generateComputedProperties(definition);

  // Generate body
  swift += `    var body: some View {\n`;
  swift += generateBody(definition, name);
  swift += `    }\n`;

  swift += `}\n\n`;

  // Preview
  swift += `#Preview {\n`;
  swift += `    VStack(spacing: 16) {\n`;

  if (definition.variants.variant) {
    for (const v of definition.variants.variant.values) {
      const previewProps = buildPreviewProps(definition, v);
      swift += `        ${name}(${previewProps})\n`;
    }
  } else {
    swift += `        ${name}(${buildPreviewProps(definition)})\n`;
  }

  swift += `    }\n`;
  swift += `    .padding()\n`;
  swift += `}\n`;

  return swift;
}

function generateComputedProperties(definition: ResolvedComponent['definition']): string {
  let swift = '';

  // Background color computed property
  if (definition.tokenMapping.background) {
    swift += `    private var backgroundColor: Color {\n`;
    if (definition.variants.variant) {
      swift += `        switch variant {\n`;
      for (const v of definition.variants.variant.values) {
        if (v === 'ghost' || v === 'outline') {
          swift += `        case .${v}: return .clear\n`;
        } else {
          swift += `        case .${v}: return Color.DesignSystem.color_${v}\n`;
        }
      }
      swift += `        }\n`;
    } else {
      swift += `        return Color.DesignSystem.color_primary\n`;
    }
    swift += `    }\n\n`;
  }

  // Text color computed property
  if (definition.tokenMapping.textColor) {
    swift += `    private var textColor: Color {\n`;
    if (definition.variants.variant) {
      swift += `        switch variant {\n`;
      for (const v of definition.variants.variant.values) {
        if (v === 'primary' || v === 'secondary') {
          swift += `        case .${v}: return .white\n`;
        } else {
          swift += `        case .${v}: return Color.DesignSystem.color_${v}\n`;
        }
      }
      swift += `        }\n`;
    } else {
      swift += `        return .white\n`;
    }
    swift += `    }\n\n`;
  }

  // Padding computed properties
  if (definition.tokenMapping.paddingX || definition.tokenMapping.paddingY) {
    swift += `    private var horizontalPadding: CGFloat {\n`;
    if (definition.variants.size) {
      swift += `        switch size {\n`;
      for (const s of definition.variants.size.values) {
        const padding = s === 'sm' ? 12 : s === 'md' ? 16 : 24;
        swift += `        case .${s}: return ${padding}\n`;
      }
      swift += `        }\n`;
    } else {
      swift += `        return 16\n`;
    }
    swift += `    }\n\n`;

    swift += `    private var verticalPadding: CGFloat {\n`;
    if (definition.variants.size) {
      swift += `        switch size {\n`;
      for (const s of definition.variants.size.values) {
        const padding = s === 'sm' ? 6 : s === 'md' ? 10 : 14;
        swift += `        case .${s}: return ${padding}\n`;
      }
      swift += `        }\n`;
    } else {
      swift += `        return 10\n`;
    }
    swift += `    }\n\n`;
  }

  // Font size computed property
  if (definition.tokenMapping.fontSize) {
    swift += `    private var fontSize: CGFloat {\n`;
    if (definition.variants.size) {
      swift += `        switch size {\n`;
      for (const s of definition.variants.size.values) {
        const size = s === 'sm' ? 14 : s === 'md' ? 16 : 18;
        swift += `        case .${s}: return ${size}\n`;
      }
      swift += `        }\n`;
    } else {
      swift += `        return 16\n`;
    }
    swift += `    }\n\n`;
  }

  return swift;
}

function generateBody(definition: ResolvedComponent['definition'], name: string): string {
  const isButton = definition.name === 'Button';
  const hasLabel = 'label' in definition.props;
  let body = '';

  if (isButton || definition.props.onPress) {
    body += `        Button(action: { onPress?() }) {\n`;
    body += `            HStack(spacing: 8) {\n`;

    if (definition.slots.leadingIcon) {
      body += `                // Leading icon slot\n`;
    }
    if (hasLabel) {
      body += `                Text(label)\n`;
      body += `                    .font(.system(size: fontSize))\n`;
    }
    if (definition.slots.trailingIcon) {
      body += `                // Trailing icon slot\n`;
    }

    body += `            }\n`;
    body += `        }\n`;
    body += `        .padding(.horizontal, horizontalPadding)\n`;
    body += `        .padding(.vertical, verticalPadding)\n`;
    body += `        .background(backgroundColor)\n`;
    body += `        .foregroundColor(textColor)\n`;

    if (definition.tokenMapping.borderRadius) {
      body += `        .cornerRadius(DesignSpacing.component_${definition.name.toLowerCase()}_borderRadius)\n`;
    }

    if (definition.tokenMapping.borderColor) {
      body += `        .overlay(\n`;
      body += `            RoundedRectangle(cornerRadius: DesignSpacing.component_${definition.name.toLowerCase()}_borderRadius)\n`;
      body += `                .stroke(variant == .outline ? textColor : .clear, lineWidth: 1)\n`;
      body += `        )\n`;
    }

    if (definition.props.disabled) {
      body += `        .disabled(disabled)\n`;
      body += `        .opacity(disabled ? 0.6 : 1.0)\n`;
    }
  } else {
    // Non-button component - generate as a basic VStack/HStack
    body += `        VStack {\n`;
    for (const [slotName] of Object.entries(definition.slots)) {
      body += `            // ${slotName} slot\n`;
    }
    if (hasLabel) {
      body += `            Text(label)\n`;
    }
    body += `        }\n`;
    body += `        .padding(.horizontal, horizontalPadding)\n`;
    body += `        .padding(.vertical, verticalPadding)\n`;
    body += `        .background(backgroundColor)\n`;

    if (definition.tokenMapping.borderRadius) {
      body += `        .cornerRadius(DesignSpacing.component_${definition.name.toLowerCase()}_borderRadius)\n`;
    }
  }

  return body;
}

function buildPreviewProps(definition: ResolvedComponent['definition'], variant?: string): string {
  const parts: string[] = [];

  if (definition.props.label) {
    parts.push(`label: "${definition.name}"`);
  }

  if (variant && definition.variants.variant) {
    parts.push(`variant: .${variant}`);
  }

  return parts.join(', ');
}

function propTypeToSwift(type: string): string {
  const map: Record<string, string> = {
    string: 'String',
    boolean: 'Bool',
    number: 'Double',
    callback: '(() -> Void)?',
    node: 'AnyView',
  };
  return map[type] ?? 'Any';
}

function swiftDefaultValue(type: string, defaultValue?: unknown): string {
  if (defaultValue !== undefined) {
    if (type === 'string') return `"${defaultValue}"`;
    if (type === 'boolean') return defaultValue ? 'true' : 'false';
    if (type === 'number') return String(defaultValue);
  }
  const map: Record<string, string> = {
    string: '""',
    boolean: 'false',
    number: '0',
    callback: 'nil',
    node: 'AnyView(EmptyView())',
  };
  return map[type] ?? 'nil';
}

function capitalize(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1);
}
