import type { GeneratorContext, GeneratedFile, ResolvedToken, ResolvedValue } from '@ryndesign/plugin-api';
import type { SwiftUIGeneratorOptions } from './index.js';

export function generateTokenFiles(ctx: GeneratorContext, options: SwiftUIGeneratorOptions): GeneratedFile[] {
  const files: GeneratedFile[] = [];
  files.push(generateColorTokens(ctx, options));
  files.push(generateDimensionTokens(ctx));
  files.push(generateTypographyTokens(ctx));
  return files;
}

function generateColorTokens(ctx: GeneratorContext, options: SwiftUIGeneratorOptions): GeneratedFile {
  const colorTokens = ctx.tokenSet.tokens.filter(t => t.$type === 'color');
  const darkTheme = ctx.tokenSet.themes.themes['dark'];

  let swift = `// Auto-generated by @ryndesign/generator-swiftui\nimport SwiftUI\n\n`;
  swift += `extension Color {\n`;
  swift += `    enum DesignSystem {\n`;

  for (const token of colorTokens) {
    const name = token.path.join('_').replace(/[.-]/g, '_');
    const hex = (token.$value as any).hex;

    if (darkTheme && options.darkMode === 'dynamic-color') {
      const darkToken = darkTheme.tokens.find(t => t.path.join('.') === token.path.join('.'));
      if (darkToken) {
        const darkHex = (darkToken.$value as any).hex;
        swift += `        static let ${name} = Color(light: Color(hex: "${hex}"), dark: Color(hex: "${darkHex}"))\n`;
        continue;
      }
    }

    swift += `        static let ${name} = Color(hex: "${hex}")\n`;
  }

  swift += `    }\n}\n\n`;

  // Add Color hex init extension
  swift += `extension Color {\n`;
  swift += `    init(hex: String) {\n`;
  swift += `        let hex = hex.trimmingCharacters(in: CharacterSet.alphanumerics.inverted)\n`;
  swift += `        var int: UInt64 = 0\n`;
  swift += `        Scanner(string: hex).scanHexInt64(&int)\n`;
  swift += `        let a, r, g, b: UInt64\n`;
  swift += `        switch hex.count {\n`;
  swift += `        case 6: (a, r, g, b) = (255, int >> 16 & 0xFF, int >> 8 & 0xFF, int & 0xFF)\n`;
  swift += `        case 8: (a, r, g, b) = (int >> 24 & 0xFF, int >> 16 & 0xFF, int >> 8 & 0xFF, int & 0xFF)\n`;
  swift += `        default: (a, r, g, b) = (255, 0, 0, 0)\n`;
  swift += `        }\n`;
  swift += `        self.init(.sRGB, red: Double(r) / 255, green: Double(g) / 255, blue: Double(b) / 255, opacity: Double(a) / 255)\n`;
  swift += `    }\n\n`;

  if (options.darkMode === 'dynamic-color') {
    swift += `    init(light: Color, dark: Color) {\n`;
    swift += `        self.init(uiColor: UIColor { traitCollection in\n`;
    swift += `            traitCollection.userInterfaceStyle == .dark\n`;
    swift += `                ? UIColor(dark) : UIColor(light)\n`;
    swift += `        })\n`;
    swift += `    }\n`;
  }
  swift += `}\n`;

  return { path: 'DesignTokens+Color.swift', content: swift, language: 'swift' };
}

function generateDimensionTokens(ctx: GeneratorContext): GeneratedFile {
  const dimTokens = ctx.tokenSet.tokens.filter(t => t.$type === 'dimension');
  let swift = `// Auto-generated by @ryndesign/generator-swiftui\nimport SwiftUI\n\n`;
  swift += `enum DesignSpacing {\n`;
  for (const token of dimTokens) {
    const name = token.path.join('_').replace(/[.-]/g, '_');
    const value = (token.$value as any).value;
    swift += `    static let ${name}: CGFloat = ${value}\n`;
  }
  swift += `}\n`;
  return { path: 'DesignTokens+Spacing.swift', content: swift, language: 'swift' };
}

function generateTypographyTokens(ctx: GeneratorContext): GeneratedFile {
  const typoTokens = ctx.tokenSet.tokens.filter(t => t.$type === 'typography');
  let swift = `// Auto-generated by @ryndesign/generator-swiftui\nimport SwiftUI\n\n`;
  swift += `extension Font {\n    enum DesignSystem {\n`;
  for (const token of typoTokens) {
    const name = token.path.join('_').replace(/[.-]/g, '_');
    const val = token.$value as any;
    const size = parseFloat(val.fontSize) || 16;
    const weight = fontWeightToSwift(val.fontWeight);
    swift += `        static let ${name} = Font.system(size: ${size}, weight: ${weight})\n`;
  }
  swift += `    }\n}\n`;
  return { path: 'DesignTokens+Typography.swift', content: swift, language: 'swift' };
}

function fontWeightToSwift(weight: number): string {
  if (weight <= 100) return '.ultraLight';
  if (weight <= 200) return '.thin';
  if (weight <= 300) return '.light';
  if (weight <= 400) return '.regular';
  if (weight <= 500) return '.medium';
  if (weight <= 600) return '.semibold';
  if (weight <= 700) return '.bold';
  if (weight <= 800) return '.heavy';
  return '.black';
}
