import type { GeneratorContext, GeneratedFile, ResolvedComponent } from '@ryndesign/plugin-api';
import type { RailsGeneratorOptions } from './index.js';

export function generateComponentFile(comp: ResolvedComponent, ctx: GeneratorContext, options: RailsGeneratorOptions): GeneratedFile[] {
  const { definition } = comp;
  const name = definition.name;
  const snakeCase = name.replace(/([a-z])([A-Z])/g, '$1_$2').toLowerCase();
  const kebab = name.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();

  const files: GeneratedFile[] = [];

  // Ruby component class
  files.push(generateRubyComponent(definition, snakeCase));

  // ERB template
  files.push(generateErbTemplate(definition, snakeCase, kebab));

  // SCSS stylesheet
  files.push(generateComponentScss(comp, snakeCase, kebab));

  return files;
}

function generateRubyComponent(definition: ResolvedComponent['definition'], snakeCase: string): GeneratedFile {
  const name = definition.name;
  const initParams = Object.entries(definition.props)
    .map(([k, v]) => {
      if (v.required) return `${k}:`;
      return `${k}: ${getRubyDefault(v.type)}`;
    })
    .concat(
      Object.entries(definition.variants).map(([k, v]) =>
        `${k}: :${v.default}`
      )
    )
    .concat(['disabled: false'])
    .join(', ');

  const instanceVars = Object.keys(definition.props)
    .map(k => `    @${k} = ${k}`)
    .concat(
      Object.keys(definition.variants).map(k => `    @${k} = ${k}`)
    )
    .concat(['    @disabled = disabled'])
    .join('\n');

  const content = `# frozen_string_literal: true

# Auto-generated by @ryndesign/generator-rails
class ${name}Component < ViewComponent::Base
  def initialize(${initParams})
${instanceVars}
  end
end
`;

  return { path: `app/components/${snakeCase}_component.rb`, content, language: 'ruby' };
}

function generateErbTemplate(definition: ResolvedComponent['definition'], snakeCase: string, kebab: string): GeneratedFile {
  const name = definition.name;
  const tag = getElementTag(name);

  const variantClasses = Object.keys(definition.variants)
    .map(k => `${kebab}--<%= @${k} %>`)
    .join(' ');

  const content = `<%# Auto-generated by @ryndesign/generator-rails %>
<${tag} class="${kebab} ${variantClasses} <%= '${kebab}--disabled' if @disabled %>" <%= 'disabled' if @disabled %>>
  <%= @label %>
</${tag}>
`;

  return { path: `app/components/${snakeCase}_component.html.erb`, content, language: 'erb' };
}

function generateComponentScss(comp: ResolvedComponent, snakeCase: string, base: string): GeneratedFile {
  const { definition, variantTokens } = comp;
  const defaultVariant = definition.variants.variant?.default ?? 'primary';
  const defaultSize = definition.variants.size?.default ?? 'md';

  let css = `// Auto-generated by @ryndesign/generator-rails\n`;

  // Base styles
  css += `.${base} {\n`;
  const baseTokens = variantTokens?.[defaultVariant]?.[defaultSize];
  if (baseTokens) {
    for (const [prop, token] of Object.entries(baseTokens)) {
      const cssProp = tokenMappingToCssProp(prop);
      if (cssProp) {
        css += `  ${cssProp}: var(--${token.path.join('-')});\n`;
      }
    }
  } else {
    for (const [prop, path] of Object.entries(definition.tokenMapping)) {
      const cssProp = tokenMappingToCssProp(prop);
      if (!cssProp) continue;
      const resolved = (path as string)
        .replace('{variant}', defaultVariant)
        .replace('{size}', defaultSize);
      css += `  ${cssProp}: var(--${resolved.replace(/\./g, '-')});\n`;
    }
  }
  css += `  cursor: pointer;\n`;
  css += `  border: none;\n`;
  css += `  display: inline-flex;\n`;
  css += `  align-items: center;\n`;
  css += `  gap: 8px;\n`;
  css += `  transition: background-color 150ms ease, color 150ms ease;\n\n`;

  // Variant styles (nested with &)
  if (definition.variants.variant) {
    for (const variant of definition.variants.variant.values) {
      css += `  &--${variant} {\n`;
      const vTokens = variantTokens?.[variant]?.[defaultSize];
      if (vTokens) {
        for (const [prop, token] of Object.entries(vTokens)) {
          if (definition.tokenMapping[prop]?.includes('{variant}')) {
            const cssProp = tokenMappingToCssProp(prop);
            if (cssProp) {
              css += `    ${cssProp}: var(--${token.path.join('-')});\n`;
            }
          }
        }
      } else {
        for (const [prop, tokenPath] of Object.entries(definition.tokenMapping)) {
          if (tokenPath.includes('{variant}')) {
            const cssProp = tokenMappingToCssProp(prop);
            if (cssProp) {
              const resolvedPath = tokenPath.replace('{variant}', variant).replace('{size}', defaultSize);
              css += `    ${cssProp}: var(--${resolvedPath.replace(/\./g, '-')});\n`;
            }
          }
        }
      }
      css += `  }\n\n`;
    }
  }

  // Size styles
  if (definition.variants.size) {
    for (const size of definition.variants.size.values) {
      css += `  &--${size} {\n`;
      const sTokens = variantTokens?.[defaultVariant]?.[size];
      if (sTokens) {
        for (const [prop, token] of Object.entries(sTokens)) {
          if (definition.tokenMapping[prop]?.includes('{size}')) {
            const cssProp = tokenMappingToCssProp(prop);
            if (cssProp) {
              css += `    ${cssProp}: var(--${token.path.join('-')});\n`;
            }
          }
        }
      } else {
        for (const [prop, tokenPath] of Object.entries(definition.tokenMapping)) {
          if (tokenPath.includes('{size}')) {
            const cssProp = tokenMappingToCssProp(prop);
            if (cssProp) {
              const resolvedPath = tokenPath.replace('{size}', size).replace('{variant}', defaultVariant);
              css += `    ${cssProp}: var(--${resolvedPath.replace(/\./g, '-')});\n`;
            }
          }
        }
      }
      css += `  }\n\n`;
    }
  }

  // State styles
  for (const [state, stateConfig] of Object.entries(definition.states)) {
    for (const [prop, tokenPath] of Object.entries(stateConfig.tokenOverrides)) {
      const cssProp = tokenMappingToCssProp(prop);
      if (!cssProp) continue;
      if (state === 'disabled') {
        css += `  &--disabled {\n`;
        const resolvedPath = tokenPath.replace(/\{variant\}/g, defaultVariant);
        css += `    ${cssProp}: var(--${resolvedPath.replace(/\./g, '-')});\n`;
        css += `    cursor: not-allowed;\n`;
        css += `    opacity: 0.5;\n`;
        css += `    pointer-events: none;\n`;
        css += `  }\n\n`;
      } else {
        const pseudo = state === 'hover' ? ':hover:not(:disabled)' : state === 'pressed' ? ':active:not(:disabled)' : `:${state}`;
        if (definition.variants.variant) {
          for (const variant of definition.variants.variant.values) {
            css += `  &--${variant}${pseudo} {\n`;
            const resolvedPath = tokenPath.replace('{variant}', variant);
            css += `    ${cssProp}: var(--${resolvedPath.replace(/\./g, '-')});\n`;
            css += `  }\n\n`;
          }
        }
      }
    }
  }

  css += `}\n`;

  return { path: `app/components/${snakeCase}_component.scss`, content: css, language: 'scss' };
}

function getRubyDefault(type: string): string {
  return { string: "''", boolean: 'false', number: '0', callback: 'nil', node: 'nil' }[type] ?? 'nil';
}

function getElementTag(name: string): string {
  return { Button: 'button', Input: 'input', Card: 'div', Checkbox: 'label', Toggle: 'button', Badge: 'span', Avatar: 'div' }[name] ?? 'div';
}

function tokenMappingToCssProp(mapping: string): string | null {
  return { background: 'background-color', textColor: 'color', borderRadius: 'border-radius', paddingX: 'padding-inline', paddingY: 'padding-block', fontSize: 'font-size', borderColor: 'border-color' }[mapping] ?? null;
}
