import type { GeneratorContext, GeneratedFile, ResolvedComponent } from '@ryndesign/plugin-api';
import type { RailsGeneratorOptions } from './index.js';

export function generateComponentFile(comp: ResolvedComponent, ctx: GeneratorContext, options: RailsGeneratorOptions): GeneratedFile[] {
  const { definition } = comp;
  const name = definition.name;
  const snakeCase = name.replace(/([a-z])([A-Z])/g, '$1_$2').toLowerCase();
  const kebab = name.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();

  const files: GeneratedFile[] = [];

  // Ruby component class
  files.push(generateRubyComponent(definition, snakeCase));

  // ERB template
  files.push(generateErbTemplate(definition, snakeCase, kebab));

  // SCSS stylesheet
  files.push(generateComponentScss(definition, snakeCase, kebab));

  return files;
}

function generateRubyComponent(definition: any, snakeCase: string): GeneratedFile {
  const name = definition.name;
  const initParams = Object.entries(definition.props)
    .map(([k, v]: [string, any]) => {
      if (v.required) return `${k}:`;
      return `${k}: ${getRubyDefault(v.type)}`;
    })
    .concat(
      Object.entries(definition.variants).map(([k, v]: [string, any]) =>
        `${k}: :${v.default}`
      )
    )
    .concat(['disabled: false'])
    .join(', ');

  const instanceVars = Object.keys(definition.props)
    .map(k => `    @${k} = ${k}`)
    .concat(
      Object.keys(definition.variants).map(k => `    @${k} = ${k}`)
    )
    .concat(['    @disabled = disabled'])
    .join('\n');

  const content = `# frozen_string_literal: true

# Auto-generated by @ryndesign/generator-rails
class ${name}Component < ViewComponent::Base
  def initialize(${initParams})
${instanceVars}
  end
end
`;

  return { path: `app/components/${snakeCase}_component.rb`, content, language: 'ruby' };
}

function generateErbTemplate(definition: any, snakeCase: string, kebab: string): GeneratedFile {
  const name = definition.name;
  const tag = getElementTag(name);

  const variantClasses = Object.keys(definition.variants)
    .map(k => `${kebab}--<%= @${k} %>`)
    .join(' ');

  const content = `<%# Auto-generated by @ryndesign/generator-rails %>
<${tag} class="${kebab} ${variantClasses} <%= '${kebab}--disabled' if @disabled %>" <%= 'disabled' if @disabled %>>
  <%= @label %>
</${tag}>
`;

  return { path: `app/components/${snakeCase}_component.html.erb`, content, language: 'erb' };
}

function generateComponentScss(definition: any, snakeCase: string, kebab: string): GeneratedFile {
  const tokenStyles = Object.entries(definition.tokenMapping)
    .map(([prop, path]) => {
      const cssProp = tokenMappingToCssProp(prop);
      if (!cssProp) return '';
      const resolved = (path as string)
        .replace('{variant}', definition.variants.variant?.default ?? 'primary')
        .replace('{size}', definition.variants.size?.default ?? 'md');
      return `  ${cssProp}: var(--${resolved.replace(/\./g, '-')});`;
    })
    .filter(Boolean)
    .join('\n');

  const content = `// Auto-generated by @ryndesign/generator-rails
.${kebab} {
${tokenStyles}
  cursor: pointer;
  border: none;
  display: inline-flex;
  align-items: center;
  gap: 8px;

  &--disabled {
    opacity: 0.5;
    cursor: not-allowed;
    pointer-events: none;
  }
}
`;

  return { path: `app/components/${snakeCase}_component.scss`, content, language: 'scss' };
}

function getRubyDefault(type: string): string {
  return { string: "''", boolean: 'false', number: '0', callback: 'nil', node: 'nil' }[type] ?? 'nil';
}

function getElementTag(name: string): string {
  return { Button: 'button', Input: 'input', Card: 'div', Checkbox: 'label', Toggle: 'button', Badge: 'span', Avatar: 'div' }[name] ?? 'div';
}

function tokenMappingToCssProp(mapping: string): string | null {
  return { background: 'background-color', textColor: 'color', borderRadius: 'border-radius', paddingX: 'padding-inline', paddingY: 'padding-block', fontSize: 'font-size' }[mapping] ?? null;
}
