import type { GeneratorContext, GeneratedFile, ResolvedToken, ResolvedValue } from '@ryndesign/plugin-api';
import type { RailsGeneratorOptions } from './index.js';

export function generateTokenFiles(ctx: GeneratorContext, options: RailsGeneratorOptions): GeneratedFile[] {
  const files: GeneratedFile[] = [];

  // SCSS variables
  files.push(generateScssVariables(ctx));

  // CSS custom properties
  files.push(generateCssCustomProperties(ctx, options));

  return files;
}

function generateScssVariables(ctx: GeneratorContext): GeneratedFile {
  let scss = '// Auto-generated by @ryndesign/generator-rails\n// SCSS token variables\n\n';

  for (const token of ctx.tokenSet.tokens) {
    const varName = token.path.join('-');
    scss += `$${varName}: ${resolvedValueToCss(token.$value)};\n`;
  }

  scss += '\n// Dark theme overrides\n';
  for (const [key, theme] of Object.entries(ctx.tokenSet.themes.themes)) {
    if (theme.tokens.length === 0) continue;
    scss += `\n// Theme: ${key}\n`;
    for (const token of theme.tokens) {
      const varName = token.path.join('-');
      scss += `$${varName}--${key}: ${resolvedValueToCss(token.$value)};\n`;
    }
  }

  return { path: '_tokens.scss', content: scss, language: 'scss' };
}

function generateCssCustomProperties(ctx: GeneratorContext, options: RailsGeneratorOptions): GeneratedFile {
  const { tokens, themes } = ctx.tokenSet;
  let css = '// Auto-generated by @ryndesign/generator-rails\n// CSS custom properties for runtime theming\n\n';
  css += ':root {\n';
  for (const token of tokens) {
    css += `  --${token.path.join('-')}: ${resolvedValueToCss(token.$value)};\n`;
  }
  css += '}\n\n';

  for (const [key, theme] of Object.entries(themes.themes)) {
    if (theme.tokens.length === 0) continue;
    if (options.darkMode !== 'class') {
      css += `@media (prefers-color-scheme: ${key}) {\n  :root {\n`;
      for (const token of theme.tokens) {
        css += `    --${token.path.join('-')}: ${resolvedValueToCss(token.$value)};\n`;
      }
      css += '  }\n}\n\n';
    }
    if (options.darkMode !== 'media') {
      css += `.theme-${key} {\n`;
      for (const token of theme.tokens) {
        css += `  --${token.path.join('-')}: ${resolvedValueToCss(token.$value)};\n`;
      }
      css += '}\n\n';
    }
  }

  return { path: '_tokens-custom-properties.scss', content: css, language: 'scss' };
}

function resolvedValueToCss(value: ResolvedValue): string {
  switch (value.type) {
    case 'color': return value.hex;
    case 'dimension': return `${value.value}${value.unit}`;
    case 'fontFamily': return value.value.join(', ');
    case 'fontWeight': return String(value.value);
    case 'duration': return `${value.value}${value.unit}`;
    case 'number': return String(value.value);
    case 'shadow': return `${value.offsetX} ${value.offsetY} ${value.blur} ${value.spread} ${value.color}`;
    case 'border': return `${value.width} ${value.style} ${value.color}`;
    default: return '';
  }
}
