import type { GeneratorContext, GeneratedFile, ResolvedComponent } from '@ryndesign/plugin-api';
import type { VueGeneratorOptions } from './index.js';

export function generateComponentFile(comp: ResolvedComponent, ctx: GeneratorContext, options: VueGeneratorOptions): GeneratedFile[] {
  const { definition } = comp;
  const name = definition.name;
  const kebab = name.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();

  const propsInterface = Object.entries(definition.props)
    .map(([k, v]) => `  ${k}${v.required ? '' : '?'}: ${propTypeToTs(v.type)};`)
    .concat(
      Object.entries(definition.variants).map(([k, v]) =>
        `  ${k}?: ${v.values.map((val: string) => `'${val}'`).join(' | ')};`
      )
    )
    .join('\n');

  const variantDefaults = Object.entries(definition.variants)
    .map(([k, v]) => `    ${k}: '${v.default}'`)
    .join(',\n');

  const tokenStyles = Object.entries(definition.tokenMapping)
    .map(([prop, path]) => {
      const cssProp = tokenMappingToCssProp(prop);
      if (!cssProp) return '';
      const resolved = (path as string)
        .replace('{variant}', definition.variants.variant?.default ?? 'primary')
        .replace('{size}', definition.variants.size?.default ?? 'md');
      return `  ${cssProp}: var(--${resolved.replace(/\./g, '-')});`;
    })
    .filter(Boolean)
    .join('\n');

  const content = `<!-- Auto-generated by @ryndesign/generator-vue -->
<script setup lang="ts">
import { computed } from 'vue';

interface ${name}Props {
${propsInterface}
}

const props = withDefaults(defineProps<${name}Props>(), {
${variantDefaults},
    disabled: false,
});

const emit = defineEmits<{
  press: [];
}>();

const classes = computed(() => [
  '${kebab}',
  \`${kebab}--\${props.variant}\`,
  \`${kebab}--\${props.size}\`,
  props.disabled && '${kebab}--disabled',
].filter(Boolean).join(' '));
</script>

<template>
  <${getElementTag(name)}
    :class="classes"
    :disabled="disabled"
    @click="emit('press')"
  >
    <slot name="leadingIcon" />
    <span class="${kebab}__label">{{ label }}</span>
    <slot name="trailingIcon" />
  </${getElementTag(name)}>
</template>

<style scoped>
.${kebab} {
${tokenStyles}
  cursor: pointer;
  border: none;
  display: inline-flex;
  align-items: center;
  gap: 8px;
}
</style>
`;

  return [{ path: `components/${name}.vue`, content, language: 'vue' }];
}

function propTypeToTs(type: string): string {
  return { string: 'string', boolean: 'boolean', number: 'number', callback: '() => void', node: 'any' }[type] ?? 'unknown';
}

function getElementTag(name: string): string {
  return { Button: 'button', Input: 'input', Card: 'div', Checkbox: 'label', Toggle: 'button', Badge: 'span', Avatar: 'div' }[name] ?? 'div';
}

function tokenMappingToCssProp(mapping: string): string | null {
  return { background: 'background-color', textColor: 'color', borderRadius: 'border-radius', paddingX: 'padding-inline', paddingY: 'padding-block', fontSize: 'font-size' }[mapping] ?? null;
}
