import type { GeneratorContext, GeneratedFile, ResolvedToken, ResolvedValue } from '@ryndesign/plugin-api';
import type { VueGeneratorOptions } from './index.js';

export function generateTokenFiles(ctx: GeneratorContext, options: VueGeneratorOptions): GeneratedFile[] {
  const files: GeneratedFile[] = [];

  // CSS custom properties (shared with react logic)
  files.push(generateCssFile(ctx, options));

  // TypeScript token constants
  if (options.typescript !== false) {
    files.push(generateTsTokens(ctx));
  }

  // Vue composable for theming
  files.push(generateUseTheme(ctx));

  return files;
}

function generateCssFile(ctx: GeneratorContext, options: VueGeneratorOptions): GeneratedFile {
  const { tokens, themes } = ctx.tokenSet;
  let css = ':root {\n';
  for (const token of tokens) {
    css += `  --${token.path.join('-')}: ${resolvedValueToCss(token.$value)};\n`;
  }
  css += '}\n\n';

  for (const [key, theme] of Object.entries(themes.themes)) {
    if (theme.tokens.length === 0) continue;
    if (options.darkMode !== 'class') {
      css += `@media (prefers-color-scheme: ${key}) {\n  :root {\n`;
      for (const token of theme.tokens) {
        css += `    --${token.path.join('-')}: ${resolvedValueToCss(token.$value)};\n`;
      }
      css += '  }\n}\n\n';
    }
    if (options.darkMode !== 'media') {
      css += `[data-theme="${key}"] {\n`;
      for (const token of theme.tokens) {
        css += `  --${token.path.join('-')}: ${resolvedValueToCss(token.$value)};\n`;
      }
      css += '}\n\n';
    }
  }

  return { path: 'tokens.css', content: css, language: 'css' };
}

function generateTsTokens(ctx: GeneratorContext): GeneratedFile {
  let ts = '// Auto-generated by @ryndesign/generator-vue\nexport const tokens = {\n';
  for (const token of ctx.tokenSet.tokens) {
    const key = token.path.join('_').replace(/[.-]/g, '_');
    ts += `  '${key}': 'var(--${token.path.join('-')})',\n`;
  }
  ts += '} as const;\n';
  return { path: 'tokens.ts', content: ts, language: 'typescript' };
}

function generateUseTheme(ctx: GeneratorContext): GeneratedFile {
  const themes = ['light', ...Object.keys(ctx.tokenSet.themes.themes)];
  const content = `// Auto-generated by @ryndesign/generator-vue
import { ref, watchEffect, type Ref } from 'vue';

export type Theme = ${themes.map(t => `'${t}'`).join(' | ')};

const currentTheme = ref<Theme>('${ctx.tokenSet.themes.default}');

export function useTheme() {
  watchEffect(() => {
    document.documentElement.setAttribute(
      'data-theme',
      currentTheme.value === 'light' ? '' : currentTheme.value
    );
  });

  const setTheme = (theme: Theme) => { currentTheme.value = theme; };
  const toggleTheme = () => {
    currentTheme.value = currentTheme.value === 'light' ? 'dark' : 'light';
  };

  return { theme: currentTheme as Ref<Theme>, setTheme, toggleTheme };
}
`;
  return { path: 'useTheme.ts', content, language: 'typescript' };
}

function resolvedValueToCss(value: ResolvedValue): string {
  switch (value.type) {
    case 'color': return value.hex;
    case 'dimension': return `${value.value}${value.unit}`;
    case 'fontFamily': return value.value.join(', ');
    case 'fontWeight': return String(value.value);
    case 'duration': return `${value.value}${value.unit}`;
    case 'number': return String(value.value);
    case 'shadow': return `${value.offsetX} ${value.offsetY} ${value.blur} ${value.spread} ${value.color}`;
    case 'border': return `${value.width} ${value.style} ${value.color}`;
    default: return '';
  }
}
