import type { GeneratorContext, GeneratedFile, ResolvedComponent } from '@ryndesign/plugin-api';
import type { UIKitGeneratorOptions } from './index.js';

export function generateComponentFile(
  comp: ResolvedComponent,
  ctx: GeneratorContext,
  options: UIKitGeneratorOptions
): GeneratedFile[] {
  const { definition } = comp;
  const name = `DS${definition.name}`;
  const files: GeneratedFile[] = [];

  files.push({
    path: `components/${name}.swift`,
    content: generateUIKitView(comp, options),
    language: 'swift',
  });

  return files;
}

function generateUIKitView(comp: ResolvedComponent, options: UIKitGeneratorOptions): string {
  const { definition } = comp;
  const name = `DS${definition.name}`;
  const useAutoLayout = options.useAutoLayout !== false;

  let swift = `// Auto-generated by @ryndesign/generator-uikit\nimport UIKit\n\n`;

  // Generate variant enums at top level
  for (const [variantName, variant] of Object.entries(definition.variants)) {
    const enumName = `${name}${capitalize(variantName)}`;
    swift += `enum ${enumName}: String, CaseIterable {\n`;
    for (const value of variant.values) {
      swift += `    case ${value}\n`;
    }
    swift += `}\n\n`;
  }

  // Generate the UIView subclass
  swift += `class ${name}: UIControl {\n\n`;

  // MARK: - Properties
  swift += `    // MARK: - Properties\n\n`;

  for (const [propName, prop] of Object.entries(definition.props)) {
    if (prop.type === 'callback') {
      swift += `    var ${propName}: (() -> Void)?\n`;
    } else if (prop.type === 'string') {
      const defaultVal = prop.default ? `"${prop.default}"` : '""';
      swift += `    var ${propName}: String = ${defaultVal} {\n`;
      swift += `        didSet { updateAppearance() }\n`;
      swift += `    }\n`;
    } else if (prop.type === 'boolean') {
      const defaultVal = prop.default ? 'true' : 'false';
      swift += `    override var ${propName === 'disabled' ? 'isEnabled' : propName}: Bool {\n`;
      swift += `        didSet { updateAppearance() }\n`;
      swift += `    }\n`;
    }
  }

  swift += `\n`;

  for (const [variantName, variant] of Object.entries(definition.variants)) {
    const enumName = `${name}${capitalize(variantName)}`;
    swift += `    var ${variantName}: ${enumName} = .${variant.default} {\n`;
    swift += `        didSet { updateAppearance() }\n`;
    swift += `    }\n`;
  }

  swift += `\n`;

  // MARK: - UI Elements
  swift += `    // MARK: - UI Elements\n\n`;

  if (definition.props.label) {
    swift += `    private let titleLabel: UILabel = {\n`;
    swift += `        let label = UILabel()\n`;
    swift += `        label.textAlignment = .center\n`;
    swift += `        label.translatesAutoresizingMaskIntoConstraints = false\n`;
    swift += `        return label\n`;
    swift += `    }()\n\n`;
  }

  if (definition.slots.leadingIcon) {
    swift += `    private let leadingIconView: UIImageView = {\n`;
    swift += `        let imageView = UIImageView()\n`;
    swift += `        imageView.contentMode = .scaleAspectFit\n`;
    swift += `        imageView.translatesAutoresizingMaskIntoConstraints = false\n`;
    swift += `        return imageView\n`;
    swift += `    }()\n\n`;
  }

  if (definition.slots.trailingIcon) {
    swift += `    private let trailingIconView: UIImageView = {\n`;
    swift += `        let imageView = UIImageView()\n`;
    swift += `        imageView.contentMode = .scaleAspectFit\n`;
    swift += `        imageView.translatesAutoresizingMaskIntoConstraints = false\n`;
    swift += `        return imageView\n`;
    swift += `    }()\n\n`;
  }

  swift += `    private let contentStackView: UIStackView = {\n`;
  swift += `        let stack = UIStackView()\n`;
  swift += `        stack.axis = .horizontal\n`;
  swift += `        stack.alignment = .center\n`;
  swift += `        stack.spacing = 8\n`;
  swift += `        stack.translatesAutoresizingMaskIntoConstraints = false\n`;
  swift += `        return stack\n`;
  swift += `    }()\n\n`;

  // MARK: - Layout constraints
  if (useAutoLayout) {
    swift += `    private var paddingConstraints: [NSLayoutConstraint] = []\n\n`;
  }

  // MARK: - Init
  swift += `    // MARK: - Initialization\n\n`;
  swift += `    override init(frame: CGRect) {\n`;
  swift += `        super.init(frame: frame)\n`;
  swift += `        setupView()\n`;
  swift += `    }\n\n`;

  swift += `    required init?(coder: NSCoder) {\n`;
  swift += `        super.init(coder: coder)\n`;
  swift += `        setupView()\n`;
  swift += `    }\n\n`;

  // MARK: - Setup
  swift += `    // MARK: - Setup\n\n`;
  swift += `    private func setupView() {\n`;

  if (definition.slots.leadingIcon) {
    swift += `        contentStackView.addArrangedSubview(leadingIconView)\n`;
  }
  if (definition.props.label) {
    swift += `        contentStackView.addArrangedSubview(titleLabel)\n`;
  }
  if (definition.slots.trailingIcon) {
    swift += `        contentStackView.addArrangedSubview(trailingIconView)\n`;
  }

  swift += `        addSubview(contentStackView)\n\n`;

  if (useAutoLayout) {
    swift += `        NSLayoutConstraint.activate([\n`;
    swift += `            contentStackView.centerXAnchor.constraint(equalTo: centerXAnchor),\n`;
    swift += `            contentStackView.centerYAnchor.constraint(equalTo: centerYAnchor),\n`;
    swift += `        ])\n\n`;
    swift += `        updatePaddingConstraints()\n`;
  }

  swift += `        addTarget(self, action: #selector(handleTap), for: .touchUpInside)\n`;
  swift += `        updateAppearance()\n`;
  swift += `    }\n\n`;

  // MARK: - Actions
  swift += `    @objc private func handleTap() {\n`;
  swift += `        onPress?()\n`;
  swift += `    }\n\n`;

  // MARK: - Update Appearance
  swift += `    private func updateAppearance() {\n`;
  if (definition.props.label) {
    swift += `        titleLabel.text = label\n`;
    swift += `        titleLabel.font = currentFont\n`;
    swift += `        titleLabel.textColor = currentTextColor\n`;
  }
  swift += `        backgroundColor = currentBackgroundColor\n`;
  swift += `        layer.cornerRadius = currentCornerRadius\n`;
  swift += `        clipsToBounds = true\n`;
  swift += `        alpha = isEnabled ? 1.0 : 0.6\n`;

  if (definition.tokenMapping.borderColor) {
    swift += `\n        if variant == .outline {\n`;
    swift += `            layer.borderWidth = 1\n`;
    swift += `            layer.borderColor = currentTextColor.cgColor\n`;
    swift += `        } else {\n`;
    swift += `            layer.borderWidth = 0\n`;
    swift += `        }\n`;
  }

  if (useAutoLayout) {
    swift += `\n        updatePaddingConstraints()\n`;
  }
  swift += `    }\n\n`;

  // Padding constraints update
  if (useAutoLayout) {
    swift += `    private func updatePaddingConstraints() {\n`;
    swift += `        NSLayoutConstraint.deactivate(paddingConstraints)\n`;
    swift += `        paddingConstraints = [\n`;
    swift += `            contentStackView.leadingAnchor.constraint(equalTo: leadingAnchor, constant: currentHorizontalPadding),\n`;
    swift += `            trailingAnchor.constraint(equalTo: contentStackView.trailingAnchor, constant: currentHorizontalPadding),\n`;
    swift += `            contentStackView.topAnchor.constraint(equalTo: topAnchor, constant: currentVerticalPadding),\n`;
    swift += `            bottomAnchor.constraint(equalTo: contentStackView.bottomAnchor, constant: currentVerticalPadding),\n`;
    swift += `        ]\n`;
    swift += `        NSLayoutConstraint.activate(paddingConstraints)\n`;
    swift += `    }\n\n`;
  }

  // Computed style properties
  swift += generateUIKitComputedProperties(comp, name);

  // Touch highlight
  swift += `    // MARK: - Touch Handling\n\n`;
  swift += `    override func touchesBegan(_ touches: Set<UITouch>, with event: UIEvent?) {\n`;
  swift += `        super.touchesBegan(touches, with: event)\n`;
  swift += `        UIView.animate(withDuration: 0.1) { self.alpha = 0.8 }\n`;
  swift += `    }\n\n`;
  swift += `    override func touchesEnded(_ touches: Set<UITouch>, with event: UIEvent?) {\n`;
  swift += `        super.touchesEnded(touches, with: event)\n`;
  swift += `        UIView.animate(withDuration: 0.1) { self.alpha = self.isEnabled ? 1.0 : 0.6 }\n`;
  swift += `    }\n\n`;
  swift += `    override func touchesCancelled(_ touches: Set<UITouch>, with event: UIEvent?) {\n`;
  swift += `        super.touchesCancelled(touches, with: event)\n`;
  swift += `        UIView.animate(withDuration: 0.1) { self.alpha = self.isEnabled ? 1.0 : 0.6 }\n`;
  swift += `    }\n\n`;

  // Intrinsic content size
  swift += `    override var intrinsicContentSize: CGSize {\n`;
  swift += `        let contentSize = contentStackView.systemLayoutSizeFitting(UIView.layoutFittingCompressedSize)\n`;
  swift += `        return CGSize(\n`;
  swift += `            width: contentSize.width + currentHorizontalPadding * 2,\n`;
  swift += `            height: contentSize.height + currentVerticalPadding * 2\n`;
  swift += `        )\n`;
  swift += `    }\n`;

  swift += `}\n`;

  return swift;
}

function generateUIKitComputedProperties(comp: ResolvedComponent, name: string): string {
  const { definition, variantTokens } = comp;
  let swift = `    // MARK: - Style Properties\n\n`;
  const defaultSize = definition.variants.size?.default ?? 'md';

  // Background color
  swift += `    private var currentBackgroundColor: UIColor {\n`;
  if (definition.variants.variant) {
    swift += `        switch variant {\n`;
    for (const v of definition.variants.variant.values) {
      const token = variantTokens?.[v]?.[defaultSize]?.background;
      if (v === 'ghost' || v === 'outline') {
        swift += `        case .${v}: return .clear\n`;
      } else if (token && token.$value.type === 'color') {
        const tokenName = token.path.join('_').replace(/[.-]/g, '_');
        swift += `        case .${v}: return UIColor.DesignSystem.${tokenName}\n`;
      } else {
        swift += `        case .${v}: return UIColor.DesignSystem.color_${v}\n`;
      }
    }
    swift += `        }\n`;
  } else {
    swift += `        return UIColor.DesignSystem.color_primary\n`;
  }
  swift += `    }\n\n`;

  // Text color
  swift += `    private var currentTextColor: UIColor {\n`;
  if (definition.variants.variant) {
    swift += `        switch variant {\n`;
    for (const v of definition.variants.variant.values) {
      const token = variantTokens?.[v]?.[defaultSize]?.textColor;
      if (token && token.$value.type === 'color') {
        const tokenName = token.path.join('_').replace(/[.-]/g, '_');
        swift += `        case .${v}: return UIColor.DesignSystem.${tokenName}\n`;
      } else if (v === 'primary' || v === 'secondary') {
        swift += `        case .${v}: return .white\n`;
      } else {
        swift += `        case .${v}: return UIColor.DesignSystem.color_${v}\n`;
      }
    }
    swift += `        }\n`;
  } else {
    swift += `        return .white\n`;
  }
  swift += `    }\n\n`;

  // Corner radius
  swift += `    private var currentCornerRadius: CGFloat {\n`;
  swift += `        return DesignSpacing.component_${definition.name.toLowerCase()}_borderRadius\n`;
  swift += `    }\n\n`;

  // Horizontal padding
  swift += `    private var currentHorizontalPadding: CGFloat {\n`;
  if (definition.variants.size) {
    swift += `        switch size {\n`;
    for (const s of definition.variants.size.values) {
      const defaultVariant = definition.variants.variant?.default ?? 'primary';
      const token = variantTokens?.[defaultVariant]?.[s]?.paddingX;
      if (token && token.$value.type === 'dimension') {
        swift += `        case .${s}: return ${token.$value.value}\n`;
      } else {
        const padding = s === 'sm' ? 12 : s === 'md' ? 16 : 24;
        swift += `        case .${s}: return ${padding}\n`;
      }
    }
    swift += `        }\n`;
  } else {
    swift += `        return 16\n`;
  }
  swift += `    }\n\n`;

  // Vertical padding
  swift += `    private var currentVerticalPadding: CGFloat {\n`;
  if (definition.variants.size) {
    swift += `        switch size {\n`;
    for (const s of definition.variants.size.values) {
      const defaultVariant = definition.variants.variant?.default ?? 'primary';
      const token = variantTokens?.[defaultVariant]?.[s]?.paddingY;
      if (token && token.$value.type === 'dimension') {
        swift += `        case .${s}: return ${token.$value.value}\n`;
      } else {
        const padding = s === 'sm' ? 6 : s === 'md' ? 10 : 14;
        swift += `        case .${s}: return ${padding}\n`;
      }
    }
    swift += `        }\n`;
  } else {
    swift += `        return 10\n`;
  }
  swift += `    }\n\n`;

  // Font
  swift += `    private var currentFont: UIFont {\n`;
  if (definition.variants.size) {
    swift += `        switch size {\n`;
    for (const s of definition.variants.size.values) {
      const defaultVariant = definition.variants.variant?.default ?? 'primary';
      const token = variantTokens?.[defaultVariant]?.[s]?.fontSize;
      if (token && token.$value.type === 'dimension') {
        swift += `        case .${s}: return .systemFont(ofSize: ${token.$value.value}, weight: .semibold)\n`;
      } else {
        const fontSize = s === 'sm' ? 14 : s === 'md' ? 16 : 18;
        swift += `        case .${s}: return .systemFont(ofSize: ${fontSize}, weight: .semibold)\n`;
      }
    }
    swift += `        }\n`;
  } else {
    swift += `        return .systemFont(ofSize: 16, weight: .semibold)\n`;
  }
  swift += `    }\n\n`;

  return swift;
}

function capitalize(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1);
}
