import { describe, it, expect } from 'vitest';
import { reactGenerator } from '../index.js';
import { buildTokenSet } from '@ryndesign/core';
import path from 'node:path';

const TEMPLATES_DIR = path.resolve(__dirname, '../../../../templates');

async function getTestContext() {
  const tokenSet = await buildTokenSet({
    tokens: ['minimal.tokens.json'],
    basePath: TEMPLATES_DIR,
    themes: {
      default: 'light',
      dark: { file: path.join(TEMPLATES_DIR, 'dark.tokens.json') },
    },
  });

  return {
    tokenSet,
    config: { outDir: 'generated/react', typescript: true, darkMode: 'media+class' as const },
    outputDir: '/tmp/test-output',
    helpers: {
      camelCase: (s: string) => s.replace(/[-_](\w)/g, (_, c) => c.toUpperCase()),
      pascalCase: (s: string) => s.replace(/(^|[-_])(\w)/g, (_, __, c) => c.toUpperCase()),
      kebabCase: (s: string) => s.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase(),
      snakeCase: (s: string) => s.replace(/([a-z])([A-Z])/g, '$1_$2').toLowerCase(),
      tokenToCssVar: (p: string[]) => `--${p.join('-')}`,
      tokenToScssVar: (p: string[]) => `$${p.join('-')}`,
      formatColor: (hex: string) => hex,
    },
  };
}

describe('React Generator', () => {
  it('should create a generator plugin with correct metadata', () => {
    const gen = reactGenerator({ typescript: true });
    expect(gen.name).toBe('react');
    expect(gen.platform).toBe('web');
    expect(gen.outputExtensions).toContain('.tsx');
    expect(gen.outputExtensions).toContain('.css');
    expect(gen.outputExtensions).toContain('.ts');
  });

  it('should generate token files with CSS, TS, and ThemeProvider', async () => {
    const gen = reactGenerator({ typescript: true, darkMode: 'media+class' });
    const ctx = await getTestContext();
    const files = await gen.generateTokens(ctx);

    expect(files.length).toBeGreaterThanOrEqual(3);

    // Should have CSS file
    const cssFile = files.find(f => f.path === 'tokens.css');
    expect(cssFile).toBeDefined();
    expect(cssFile!.content).toContain(':root');
    expect(cssFile!.content).toContain('--color-primary');

    // Should have TS file
    const tsFile = files.find(f => f.path === 'tokens.ts');
    expect(tsFile).toBeDefined();
    expect(tsFile!.content).toContain('export const tokens');

    // Should have ThemeProvider
    const themeFile = files.find(f => f.path === 'ThemeProvider.tsx');
    expect(themeFile).toBeDefined();
    expect(themeFile!.content).toContain('ThemeProvider');
    expect(themeFile!.content).toContain('useTheme');
  });

  it('should include dark mode CSS with media query and data-attribute', async () => {
    const gen = reactGenerator({ darkMode: 'media+class' });
    const ctx = await getTestContext();
    const files = await gen.generateTokens(ctx);
    const cssFile = files.find(f => f.path === 'tokens.css')!;

    expect(cssFile.content).toContain('prefers-color-scheme');
    expect(cssFile.content).toContain('[data-theme="dark"]');
  });

  it('should generate CSS with correct token values', async () => {
    const gen = reactGenerator({ darkMode: 'media+class' });
    const ctx = await getTestContext();
    const files = await gen.generateTokens(ctx);
    const cssFile = files.find(f => f.path === 'tokens.css')!;

    expect(cssFile.content).toContain('#3B82F6');
    expect(cssFile.content).toContain('--spacing-xs');
    expect(cssFile.content).toContain('4px');
  });

  it('should generate TypeScript tokens referencing CSS variables', async () => {
    const gen = reactGenerator({ typescript: true });
    const ctx = await getTestContext();
    const files = await gen.generateTokens(ctx);
    const tsFile = files.find(f => f.path === 'tokens.ts')!;

    expect(tsFile.content).toContain('var(--color-primary)');
    expect(tsFile.content).toContain('as const');
    expect(tsFile.content).toContain('Auto-generated by @ryndesign/generator-react');
  });

  it('should skip TS file when typescript is false', async () => {
    const gen = reactGenerator({ typescript: false });
    const ctx = await getTestContext();
    const files = await gen.generateTokens(ctx);
    const tsFile = files.find(f => f.path === 'tokens.ts');

    expect(tsFile).toBeUndefined();
  });

  it('should have preview adapter', () => {
    const gen = reactGenerator();
    const adapter = gen.getPreviewAdapter?.();
    expect(adapter).toBeDefined();
    expect(adapter!.previewSetup()).toBeTruthy();
  });

  it('should generate ThemeProvider with correct theme types', async () => {
    const gen = reactGenerator({ typescript: true, darkMode: 'media+class' });
    const ctx = await getTestContext();
    const files = await gen.generateTokens(ctx);
    const themeFile = files.find(f => f.path === 'ThemeProvider.tsx')!;

    expect(themeFile.content).toContain("'light'");
    expect(themeFile.content).toContain("'dark'");
    expect(themeFile.content).toContain('toggleTheme');
    expect(themeFile.content).toContain('data-theme');
  });
});
