import type { GeneratorContext, GeneratedFile, ResolvedComponent } from '@ryndesign/plugin-api';
import type { CssGeneratorOptions } from './index.js';

export function generateComponentFile(
  comp: ResolvedComponent,
  ctx: GeneratorContext,
  options: CssGeneratorOptions
): GeneratedFile[] {
  const { definition, variantTokens } = comp;
  const name = definition.name;
  const base = name.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();
  const prefix = options.prefix ? `${options.prefix}-` : '';
  const ext = options.scss ? '.scss' : '.css';

  const content = options.scss
    ? generateScss(comp, base, prefix)
    : generateCss(comp, base, prefix);

  return [{ path: `components/${base}${ext}`, content, language: options.scss ? 'scss' : 'css' }];
}

function generateCss(comp: ResolvedComponent, base: string, prefix: string): string {
  const { definition, variantTokens } = comp;
  const defaultVariant = definition.variants.variant?.default ?? 'primary';
  const defaultSize = definition.variants.size?.default ?? 'md';

  let css = `/* Auto-generated by @ryndesign/generator-css */\n\n`;

  // Base styles
  css += `.${base} {\n`;
  const baseTokens = variantTokens?.[defaultVariant]?.[defaultSize];
  if (baseTokens) {
    for (const [prop, token] of Object.entries(baseTokens)) {
      const cssProp = tokenMappingToCssProp(prop);
      if (cssProp) {
        css += `  ${cssProp}: var(--${prefix}${token.path.join('-')});\n`;
      }
    }
  } else {
    for (const [prop, tokenPath] of Object.entries(definition.tokenMapping)) {
      const cssProp = tokenMappingToCssProp(prop);
      if (!cssProp) continue;
      const resolved = tokenPath
        .replace('{variant}', defaultVariant)
        .replace('{size}', defaultSize);
      css += `  ${cssProp}: var(--${prefix}${resolved.replace(/\./g, '-')});\n`;
    }
  }
  css += `  display: inline-flex;\n`;
  css += `  align-items: center;\n`;
  css += `  gap: 8px;\n`;
  css += `  transition: background-color 150ms ease, color 150ms ease;\n`;
  css += `}\n\n`;

  // Variant styles
  if (definition.variants.variant) {
    for (const variant of definition.variants.variant.values) {
      css += `.${base}--${variant} {\n`;
      const vTokens = variantTokens?.[variant]?.[defaultSize];
      if (vTokens) {
        for (const [prop, token] of Object.entries(vTokens)) {
          if (definition.tokenMapping[prop]?.includes('{variant}')) {
            const cssProp = tokenMappingToCssProp(prop);
            if (cssProp) {
              css += `  ${cssProp}: var(--${prefix}${token.path.join('-')});\n`;
            }
          }
        }
      }
      css += `}\n\n`;
    }
  }

  // Size styles
  if (definition.variants.size) {
    for (const size of definition.variants.size.values) {
      css += `.${base}--${size} {\n`;
      const sTokens = variantTokens?.[defaultVariant]?.[size];
      if (sTokens) {
        for (const [prop, token] of Object.entries(sTokens)) {
          if (definition.tokenMapping[prop]?.includes('{size}')) {
            const cssProp = tokenMappingToCssProp(prop);
            if (cssProp) {
              css += `  ${cssProp}: var(--${prefix}${token.path.join('-')});\n`;
            }
          }
        }
      }
      css += `}\n\n`;
    }
  }

  // State styles
  for (const [state, stateConfig] of Object.entries(definition.states)) {
    for (const [prop, tokenPath] of Object.entries(stateConfig.tokenOverrides)) {
      const cssProp = tokenMappingToCssProp(prop);
      if (!cssProp) continue;

      if (state === 'disabled') {
        css += `.${base}--disabled {\n`;
        const resolvedPath = tokenPath.replace(/\{variant\}/g, defaultVariant);
        css += `  ${cssProp}: var(--${prefix}${resolvedPath.replace(/\./g, '-')});\n`;
        css += `  cursor: not-allowed;\n`;
        css += `  opacity: 0.6;\n`;
        css += `  pointer-events: none;\n`;
        css += `}\n\n`;
      } else {
        const pseudo = state === 'hover' ? ':hover:not(:disabled)' : state === 'pressed' ? ':active:not(:disabled)' : `:${state}`;
        if (definition.variants.variant) {
          for (const variant of definition.variants.variant.values) {
            css += `.${base}--${variant}${pseudo} {\n`;
            const resolvedPath = tokenPath.replace('{variant}', variant);
            css += `  ${cssProp}: var(--${prefix}${resolvedPath.replace(/\./g, '-')});\n`;
            css += `}\n\n`;
          }
        }
      }
    }
  }

  return css;
}

function generateScss(comp: ResolvedComponent, base: string, prefix: string): string {
  const { definition, variantTokens } = comp;
  const defaultVariant = definition.variants.variant?.default ?? 'primary';
  const defaultSize = definition.variants.size?.default ?? 'md';

  let scss = `// Auto-generated by @ryndesign/generator-css\n\n`;

  scss += `.${base} {\n`;
  const baseTokens = variantTokens?.[defaultVariant]?.[defaultSize];
  if (baseTokens) {
    for (const [prop, token] of Object.entries(baseTokens)) {
      const cssProp = tokenMappingToCssProp(prop);
      if (cssProp) {
        scss += `  ${cssProp}: var(--${prefix}${token.path.join('-')});\n`;
      }
    }
  } else {
    for (const [prop, tokenPath] of Object.entries(definition.tokenMapping)) {
      const cssProp = tokenMappingToCssProp(prop);
      if (!cssProp) continue;
      const resolved = tokenPath
        .replace('{variant}', defaultVariant)
        .replace('{size}', defaultSize);
      scss += `  ${cssProp}: var(--${prefix}${resolved.replace(/\./g, '-')});\n`;
    }
  }
  scss += `  display: inline-flex;\n`;
  scss += `  align-items: center;\n`;
  scss += `  gap: 8px;\n`;
  scss += `  transition: background-color 150ms ease, color 150ms ease;\n\n`;

  // Variant styles (nested)
  if (definition.variants.variant) {
    for (const variant of definition.variants.variant.values) {
      scss += `  &--${variant} {\n`;
      const vTokens = variantTokens?.[variant]?.[defaultSize];
      if (vTokens) {
        for (const [prop, token] of Object.entries(vTokens)) {
          if (definition.tokenMapping[prop]?.includes('{variant}')) {
            const cssProp = tokenMappingToCssProp(prop);
            if (cssProp) {
              scss += `    ${cssProp}: var(--${prefix}${token.path.join('-')});\n`;
            }
          }
        }
      }
      scss += `  }\n\n`;
    }
  }

  // Size styles (nested)
  if (definition.variants.size) {
    for (const size of definition.variants.size.values) {
      scss += `  &--${size} {\n`;
      const sTokens = variantTokens?.[defaultVariant]?.[size];
      if (sTokens) {
        for (const [prop, token] of Object.entries(sTokens)) {
          if (definition.tokenMapping[prop]?.includes('{size}')) {
            const cssProp = tokenMappingToCssProp(prop);
            if (cssProp) {
              scss += `    ${cssProp}: var(--${prefix}${token.path.join('-')});\n`;
            }
          }
        }
      }
      scss += `  }\n\n`;
    }
  }

  // State styles (nested)
  for (const [state, stateConfig] of Object.entries(definition.states)) {
    for (const [prop, tokenPath] of Object.entries(stateConfig.tokenOverrides)) {
      const cssProp = tokenMappingToCssProp(prop);
      if (!cssProp) continue;

      if (state === 'disabled') {
        scss += `  &--disabled {\n`;
        const resolvedPath = tokenPath.replace(/\{variant\}/g, defaultVariant);
        scss += `    ${cssProp}: var(--${prefix}${resolvedPath.replace(/\./g, '-')});\n`;
        scss += `    cursor: not-allowed;\n`;
        scss += `    opacity: 0.6;\n`;
        scss += `    pointer-events: none;\n`;
        scss += `  }\n\n`;
      } else {
        const pseudo = state === 'hover' ? ':hover:not(:disabled)' : state === 'pressed' ? ':active:not(:disabled)' : `:${state}`;
        if (definition.variants.variant) {
          for (const variant of definition.variants.variant.values) {
            scss += `  &--${variant}${pseudo} {\n`;
            const resolvedPath = tokenPath.replace('{variant}', variant);
            scss += `    ${cssProp}: var(--${prefix}${resolvedPath.replace(/\./g, '-')});\n`;
            scss += `  }\n\n`;
          }
        }
      }
    }
  }

  scss += `}\n`;

  return scss;
}

function tokenMappingToCssProp(mapping: string): string | null {
  const map: Record<string, string> = {
    background: 'background-color',
    textColor: 'color',
    borderRadius: 'border-radius',
    paddingX: 'padding-inline',
    paddingY: 'padding-block',
    fontSize: 'font-size',
    borderColor: 'border-color',
    borderWidth: 'border-width',
  };
  return map[mapping] ?? null;
}
