import type { GeneratorContext, GeneratedFile, ResolvedValue } from '@ryndesign/plugin-api';
import type { CssGeneratorOptions } from './index.js';

export function generateTokenFiles(ctx: GeneratorContext, options: CssGeneratorOptions): GeneratedFile[] {
  const files: GeneratedFile[] = [];
  const prefix = options.prefix ? `${options.prefix}-` : '';

  // CSS custom properties
  files.push(generateCssVariables(ctx, options, prefix));

  // SCSS variables
  if (options.scss) {
    files.push(generateScssVariables(ctx, prefix));
  }

  return files;
}

function generateCssVariables(ctx: GeneratorContext, options: CssGeneratorOptions, prefix: string): GeneratedFile {
  const { tokens, themes } = ctx.tokenSet;

  let css = `/* Auto-generated by @ryndesign/generator-css */\n`;
  css += `:root {\n`;
  for (const token of tokens) {
    css += `  --${prefix}${token.path.join('-')}: ${resolvedValueToCss(token.$value)};\n`;
  }
  css += `}\n`;

  // Theme overrides
  for (const [key, theme] of Object.entries(themes.themes)) {
    if (theme.tokens.length === 0) continue;

    // Media query
    if (options.darkMode !== 'class') {
      css += `\n@media (prefers-color-scheme: ${key}) {\n`;
      css += `  :root {\n`;
      for (const token of theme.tokens) {
        css += `    --${prefix}${token.path.join('-')}: ${resolvedValueToCss(token.$value)};\n`;
      }
      css += `  }\n`;
      css += `}\n`;
    }

    // Data attribute
    if (options.darkMode !== 'media') {
      css += `\n[data-theme="${key}"] {\n`;
      for (const token of theme.tokens) {
        css += `  --${prefix}${token.path.join('-')}: ${resolvedValueToCss(token.$value)};\n`;
      }
      css += `}\n`;
    }
  }

  return { path: 'tokens.css', content: css, language: 'css' };
}

function generateScssVariables(ctx: GeneratorContext, prefix: string): GeneratedFile {
  const { tokens, themes } = ctx.tokenSet;

  let scss = `// Auto-generated by @ryndesign/generator-css\n\n`;
  scss += `// Base tokens\n`;
  for (const token of tokens) {
    scss += `$${prefix}${token.path.join('-')}: ${resolvedValueToCss(token.$value)};\n`;
  }

  // Theme maps
  for (const [key, theme] of Object.entries(themes.themes)) {
    if (theme.tokens.length === 0) continue;
    scss += `\n// ${key} theme overrides\n`;
    scss += `$theme-${key}: (\n`;
    for (const token of theme.tokens) {
      scss += `  '${token.path.join('-')}': ${resolvedValueToCss(token.$value)},\n`;
    }
    scss += `);\n`;
  }

  // Mixin for theme application
  scss += `\n// Apply theme mixin\n`;
  scss += `@mixin apply-theme($theme-map) {\n`;
  scss += `  @each $key, $value in $theme-map {\n`;
  scss += `    --${prefix}#{$key}: #{$value};\n`;
  scss += `  }\n`;
  scss += `}\n`;

  return { path: '_tokens.scss', content: scss, language: 'scss' };
}

function resolvedValueToCss(value: ResolvedValue): string {
  switch (value.type) {
    case 'color': return value.hex;
    case 'dimension': return `${value.value}${value.unit}`;
    case 'fontFamily': return value.value.join(', ');
    case 'fontWeight': return String(value.value);
    case 'duration': return `${value.value}${value.unit}`;
    case 'number': return String(value.value);
    case 'shadow': return `${value.offsetX} ${value.offsetY} ${value.blur} ${value.spread} ${value.color}`;
    case 'border': return `${value.width} ${value.style} ${value.color}`;
    default: return '';
  }
}
