import type { GeneratorContext, GeneratedFile, ResolvedComponent } from '@ryndesign/plugin-api';
import type { AndroidViewGeneratorOptions } from './index.js';

export function generateComponentFile(
  comp: ResolvedComponent,
  ctx: GeneratorContext,
  options: AndroidViewGeneratorOptions
): GeneratedFile[] {
  const { definition } = comp;
  const name = `DS${definition.name}`;
  const pkg = options.packageName ?? 'com.ryndesign.components';
  const files: GeneratedFile[] = [];

  // Generate Kotlin custom View class
  files.push({
    path: `components/${name}.kt`,
    content: generateCustomView(comp, options, pkg),
    language: 'kotlin',
  });

  // Generate XML layout
  files.push({
    path: `layout/view_${snakeCase(definition.name)}.xml`,
    content: generateXmlLayout(comp, options),
    language: 'xml',
  });

  // Generate XML attrs for the custom view
  files.push({
    path: `values/attrs_${snakeCase(definition.name)}.xml`,
    content: generateCustomAttrs(comp),
    language: 'xml',
  });

  return files;
}

function generateCustomView(comp: ResolvedComponent, options: AndroidViewGeneratorOptions, pkg: string): string {
  const { definition } = comp;
  const name = `DS${definition.name}`;
  const viewBase = definition.props.onPress ? 'FrameLayout' : 'FrameLayout';

  let kt = `// Auto-generated by @ryndesign/generator-android-view\n`;
  kt += `package ${pkg}\n\n`;

  // Imports
  kt += `import android.content.Context\n`;
  kt += `import android.content.res.ColorStateList\n`;
  kt += `import android.graphics.drawable.GradientDrawable\n`;
  kt += `import android.graphics.drawable.RippleDrawable\n`;
  kt += `import android.util.AttributeSet\n`;
  kt += `import android.util.TypedValue\n`;
  kt += `import android.view.Gravity\n`;
  kt += `import android.view.LayoutInflater\n`;
  kt += `import android.widget.FrameLayout\n`;
  kt += `import android.widget.LinearLayout\n`;
  kt += `import android.widget.TextView\n`;
  kt += `import android.widget.ImageView\n`;
  kt += `import androidx.annotation.ColorInt\n`;
  kt += `import androidx.core.content.ContextCompat\n`;
  kt += `import com.ryndesign.tokens.R\n\n`;

  // Variant enum
  for (const [variantName, variant] of Object.entries(definition.variants)) {
    const enumName = `${name}${capitalize(variantName)}`;
    kt += `enum class ${enumName}(val value: Int) {\n`;
    variant.values.forEach((v, i) => {
      kt += `    ${v.toUpperCase()}(${i})${i < variant.values.length - 1 ? ',' : ';'}\n`;
    });
    kt += `\n    companion object {\n`;
    kt += `        fun fromValue(value: Int) = entries.firstOrNull { it.value == value } ?: ${variant.default.toUpperCase()}\n`;
    kt += `    }\n`;
    kt += `}\n\n`;
  }

  // Custom View class
  kt += `class ${name} @JvmOverloads constructor(\n`;
  kt += `    context: Context,\n`;
  kt += `    attrs: AttributeSet? = null,\n`;
  kt += `    defStyleAttr: Int = 0\n`;
  kt += `) : ${viewBase}(context, attrs, defStyleAttr) {\n\n`;

  // UI elements
  kt += `    private val contentLayout: LinearLayout\n`;
  if (definition.props.label) {
    kt += `    private val titleTextView: TextView\n`;
  }
  if (definition.slots.leadingIcon) {
    kt += `    private val leadingIconView: ImageView\n`;
  }
  if (definition.slots.trailingIcon) {
    kt += `    private val trailingIconView: ImageView\n`;
  }

  kt += `\n`;

  // Properties
  if (definition.props.label) {
    kt += `    var label: String = ""\n`;
    kt += `        set(value) {\n`;
    kt += `            field = value\n`;
    kt += `            titleTextView.text = value\n`;
    kt += `        }\n\n`;
  }

  if (definition.props.disabled) {
    kt += `    override fun setEnabled(enabled: Boolean) {\n`;
    kt += `        super.setEnabled(enabled)\n`;
    kt += `        alpha = if (enabled) 1f else 0.6f\n`;
    kt += `        isClickable = enabled\n`;
    kt += `    }\n\n`;
  }

  if (definition.props.onPress) {
    kt += `    var onPress: (() -> Unit)? = null\n\n`;
  }

  for (const [variantName, variant] of Object.entries(definition.variants)) {
    const enumName = `${name}${capitalize(variantName)}`;
    kt += `    var ${variantName}: ${enumName} = ${enumName}.${variant.default.toUpperCase()}\n`;
    kt += `        set(value) {\n`;
    kt += `            field = value\n`;
    kt += `            updateAppearance()\n`;
    kt += `        }\n\n`;
  }

  // Init block
  kt += `    init {\n`;
  kt += `        val inflater = LayoutInflater.from(context)\n`;
  kt += `        inflater.inflate(R.layout.view_${snakeCase(definition.name)}, this, true)\n\n`;

  kt += `        contentLayout = findViewById(R.id.content_layout)\n`;
  if (definition.props.label) {
    kt += `        titleTextView = findViewById(R.id.title_text)\n`;
  }
  if (definition.slots.leadingIcon) {
    kt += `        leadingIconView = findViewById(R.id.leading_icon)\n`;
  }
  if (definition.slots.trailingIcon) {
    kt += `        trailingIconView = findViewById(R.id.trailing_icon)\n`;
  }

  kt += `\n`;

  // Parse custom attrs
  kt += `        attrs?.let {\n`;
  kt += `            val a = context.obtainStyledAttributes(it, R.styleable.${name})\n`;
  kt += `            try {\n`;
  if (definition.props.label) {
    kt += `                label = a.getString(R.styleable.${name}_ds_label) ?: ""\n`;
  }
  for (const [variantName, variant] of Object.entries(definition.variants)) {
    const enumName = `${name}${capitalize(variantName)}`;
    kt += `                ${variantName} = ${enumName}.fromValue(a.getInt(R.styleable.${name}_ds_${variantName}, 0))\n`;
  }
  if (definition.props.disabled) {
    kt += `                isEnabled = !a.getBoolean(R.styleable.${name}_ds_disabled, false)\n`;
  }
  kt += `            } finally {\n`;
  kt += `                a.recycle()\n`;
  kt += `            }\n`;
  kt += `        }\n\n`;

  if (definition.props.onPress) {
    kt += `        setOnClickListener { onPress?.invoke() }\n`;
  }

  kt += `        updateAppearance()\n`;
  kt += `    }\n\n`;

  // updateAppearance
  kt += `    private fun updateAppearance() {\n`;
  kt += `        val bgColor = getBackgroundColor()\n`;
  kt += `        val textColor = getTextColor()\n`;
  kt += `        val cornerRadius = resources.getDimension(R.dimen.component_${definition.name.toLowerCase()}_borderRadius)\n\n`;

  kt += `        val bgDrawable = GradientDrawable().apply {\n`;
  kt += `            setColor(bgColor)\n`;
  kt += `            this.cornerRadius = cornerRadius\n`;

  if (definition.tokenMapping.borderColor) {
    const variantEnum = `${name}Variant`;
    kt += `            if (variant == ${variantEnum}.OUTLINE) {\n`;
    kt += `                setStroke(resources.getDimensionPixelSize(R.dimen.component_${definition.name.toLowerCase()}_borderWidth), textColor)\n`;
    kt += `            }\n`;
  }

  kt += `        }\n\n`;

  kt += `        val rippleColor = ColorStateList.valueOf(adjustAlpha(textColor, 0.12f))\n`;
  kt += `        background = RippleDrawable(rippleColor, bgDrawable, null)\n\n`;

  if (definition.props.label) {
    kt += `        titleTextView.setTextColor(textColor)\n`;
    kt += `        titleTextView.setTextSize(TypedValue.COMPLEX_UNIT_SP, getFontSize())\n`;
  }

  kt += `\n        val hPadding = getHorizontalPadding()\n`;
  kt += `        val vPadding = getVerticalPadding()\n`;
  kt += `        contentLayout.setPadding(hPadding, vPadding, hPadding, vPadding)\n`;
  kt += `    }\n\n`;

  // Helper color methods
  kt += `    @ColorInt\n`;
  kt += `    private fun getBackgroundColor(): Int {\n`;
  if (definition.variants.variant) {
    const variantEnum = `${name}Variant`;
    kt += `        return when (variant) {\n`;
    for (const v of definition.variants.variant.values) {
      if (v === 'ghost' || v === 'outline') {
        kt += `            ${variantEnum}.${v.toUpperCase()} -> android.graphics.Color.TRANSPARENT\n`;
      } else {
        kt += `            ${variantEnum}.${v.toUpperCase()} -> ContextCompat.getColor(context, R.color.color_${v})\n`;
      }
    }
    kt += `        }\n`;
  } else {
    kt += `        return ContextCompat.getColor(context, R.color.color_primary)\n`;
  }
  kt += `    }\n\n`;

  kt += `    @ColorInt\n`;
  kt += `    private fun getTextColor(): Int {\n`;
  if (definition.variants.variant) {
    const variantEnum = `${name}Variant`;
    kt += `        return when (variant) {\n`;
    for (const v of definition.variants.variant.values) {
      if (v === 'primary' || v === 'secondary') {
        kt += `            ${variantEnum}.${v.toUpperCase()} -> android.graphics.Color.WHITE\n`;
      } else {
        kt += `            ${variantEnum}.${v.toUpperCase()} -> ContextCompat.getColor(context, R.color.color_${v})\n`;
      }
    }
    kt += `        }\n`;
  } else {
    kt += `        return android.graphics.Color.WHITE\n`;
  }
  kt += `    }\n\n`;

  // Size helpers
  kt += `    private fun getHorizontalPadding(): Int {\n`;
  if (definition.variants.size) {
    const sizeEnum = `${name}Size`;
    kt += `        return when (size) {\n`;
    for (const s of definition.variants.size.values) {
      const padding = s === 'sm' ? 12 : s === 'md' ? 16 : 24;
      kt += `            ${sizeEnum}.${s.toUpperCase()} -> dpToPx(${padding}f)\n`;
    }
    kt += `        }\n`;
  } else {
    kt += `        return dpToPx(16f)\n`;
  }
  kt += `    }\n\n`;

  kt += `    private fun getVerticalPadding(): Int {\n`;
  if (definition.variants.size) {
    const sizeEnum = `${name}Size`;
    kt += `        return when (size) {\n`;
    for (const s of definition.variants.size.values) {
      const padding = s === 'sm' ? 6 : s === 'md' ? 10 : 14;
      kt += `            ${sizeEnum}.${s.toUpperCase()} -> dpToPx(${padding}f)\n`;
    }
    kt += `        }\n`;
  } else {
    kt += `        return dpToPx(10f)\n`;
  }
  kt += `    }\n\n`;

  kt += `    private fun getFontSize(): Float {\n`;
  if (definition.variants.size) {
    const sizeEnum = `${name}Size`;
    kt += `        return when (size) {\n`;
    for (const s of definition.variants.size.values) {
      const fontSize = s === 'sm' ? 14 : s === 'md' ? 16 : 18;
      kt += `            ${sizeEnum}.${s.toUpperCase()} -> ${fontSize}f\n`;
    }
    kt += `        }\n`;
  } else {
    kt += `        return 16f\n`;
  }
  kt += `    }\n\n`;

  // Utility methods
  kt += `    private fun dpToPx(dp: Float): Int {\n`;
  kt += `        return TypedValue.applyDimension(\n`;
  kt += `            TypedValue.COMPLEX_UNIT_DIP, dp, resources.displayMetrics\n`;
  kt += `        ).toInt()\n`;
  kt += `    }\n\n`;

  kt += `    @ColorInt\n`;
  kt += `    private fun adjustAlpha(@ColorInt color: Int, factor: Float): Int {\n`;
  kt += `        val alpha = (android.graphics.Color.alpha(color) * factor).toInt()\n`;
  kt += `        return android.graphics.Color.argb(\n`;
  kt += `            alpha,\n`;
  kt += `            android.graphics.Color.red(color),\n`;
  kt += `            android.graphics.Color.green(color),\n`;
  kt += `            android.graphics.Color.blue(color)\n`;
  kt += `        )\n`;
  kt += `    }\n`;

  kt += `}\n`;

  return kt;
}

function generateXmlLayout(comp: ResolvedComponent, options: AndroidViewGeneratorOptions): string {
  const { definition } = comp;

  let xml = `<?xml version="1.0" encoding="utf-8"?>\n`;
  xml += `<!-- Auto-generated by @ryndesign/generator-android-view -->\n`;
  xml += `<merge xmlns:android="http://schemas.android.com/apk/res/android"\n`;
  xml += `    xmlns:tools="http://schemas.android.com/tools">\n\n`;

  xml += `    <LinearLayout\n`;
  xml += `        android:id="@+id/content_layout"\n`;
  xml += `        android:layout_width="wrap_content"\n`;
  xml += `        android:layout_height="wrap_content"\n`;
  xml += `        android:layout_gravity="center"\n`;
  xml += `        android:gravity="center"\n`;
  xml += `        android:orientation="horizontal">\n\n`;

  if (definition.slots.leadingIcon) {
    xml += `        <ImageView\n`;
    xml += `            android:id="@+id/leading_icon"\n`;
    xml += `            android:layout_width="20dp"\n`;
    xml += `            android:layout_height="20dp"\n`;
    xml += `            android:layout_marginEnd="8dp"\n`;
    xml += `            android:scaleType="fitCenter"\n`;
    xml += `            android:visibility="gone"\n`;
    xml += `            tools:visibility="visible" />\n\n`;
  }

  if (definition.props.label) {
    xml += `        <TextView\n`;
    xml += `            android:id="@+id/title_text"\n`;
    xml += `            android:layout_width="wrap_content"\n`;
    xml += `            android:layout_height="wrap_content"\n`;
    xml += `            android:gravity="center"\n`;
    xml += `            android:textSize="16sp"\n`;
    xml += `            tools:text="${definition.name}" />\n\n`;
  }

  if (definition.slots.trailingIcon) {
    xml += `        <ImageView\n`;
    xml += `            android:id="@+id/trailing_icon"\n`;
    xml += `            android:layout_width="20dp"\n`;
    xml += `            android:layout_height="20dp"\n`;
    xml += `            android:layout_marginStart="8dp"\n`;
    xml += `            android:scaleType="fitCenter"\n`;
    xml += `            android:visibility="gone"\n`;
    xml += `            tools:visibility="visible" />\n\n`;
  }

  xml += `    </LinearLayout>\n\n`;
  xml += `</merge>\n`;

  return xml;
}

function generateCustomAttrs(comp: ResolvedComponent): string {
  const { definition } = comp;
  const name = `DS${definition.name}`;

  let xml = `<?xml version="1.0" encoding="utf-8"?>\n`;
  xml += `<!-- Auto-generated by @ryndesign/generator-android-view -->\n`;
  xml += `<resources>\n\n`;

  xml += `    <declare-styleable name="${name}">\n`;

  if (definition.props.label) {
    xml += `        <attr name="ds_label" format="string" />\n`;
  }

  if (definition.props.disabled) {
    xml += `        <attr name="ds_disabled" format="boolean" />\n`;
  }

  for (const [variantName, variant] of Object.entries(definition.variants)) {
    xml += `        <attr name="ds_${variantName}" format="enum">\n`;
    variant.values.forEach((v, i) => {
      xml += `            <enum name="${v}" value="${i}" />\n`;
    });
    xml += `        </attr>\n`;
  }

  xml += `    </declare-styleable>\n\n`;
  xml += `</resources>\n`;

  return xml;
}

function snakeCase(str: string): string {
  return str.replace(/([a-z])([A-Z])/g, '$1_$2').toLowerCase();
}

function capitalize(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1);
}
