import type { GeneratorContext, GeneratedFile, ResolvedToken, ResolvedValue } from '@ryndesign/plugin-api';
import type { AndroidViewGeneratorOptions } from './index.js';

export function generateTokenFiles(ctx: GeneratorContext, options: AndroidViewGeneratorOptions): GeneratedFile[] {
  const files: GeneratedFile[] = [];

  files.push(generateColorsXml(ctx, false));
  files.push(generateColorsXml(ctx, true));
  files.push(generateDimensXml(ctx));
  files.push(generateTypographyStyles(ctx));
  files.push(generateThemeAttrs(ctx));

  return files;
}

function generateColorsXml(ctx: GeneratorContext, isDark: boolean): GeneratedFile {
  const colorTokens = ctx.tokenSet.tokens.filter(t => t.$type === 'color');
  const darkTheme = ctx.tokenSet.themes.themes['dark'];

  let xml = `<?xml version="1.0" encoding="utf-8"?>\n`;
  xml += `<!-- Auto-generated by @ryndesign/generator-android-view -->\n`;
  xml += `<resources>\n`;

  for (const token of colorTokens) {
    const name = token.path.join('_').replace(/[.-]/g, '_');

    if (isDark && darkTheme) {
      const darkToken = darkTheme.tokens.find(t => t.path.join('.') === token.path.join('.'));
      if (darkToken) {
        const hex = normalizeHexForAndroid((darkToken.$value as any).hex);
        xml += `    <color name="${name}">${hex}</color>\n`;
        continue;
      }
    }

    const hex = normalizeHexForAndroid((token.$value as any).hex);
    xml += `    <color name="${name}">${hex}</color>\n`;
  }

  xml += `</resources>\n`;

  const dir = isDark ? 'values-night' : 'values';
  return { path: `${dir}/colors.xml`, content: xml, language: 'xml' };
}

function generateDimensXml(ctx: GeneratorContext): GeneratedFile {
  const dimTokens = ctx.tokenSet.tokens.filter(t => t.$type === 'dimension');

  let xml = `<?xml version="1.0" encoding="utf-8"?>\n`;
  xml += `<!-- Auto-generated by @ryndesign/generator-android-view -->\n`;
  xml += `<resources>\n`;

  for (const token of dimTokens) {
    const name = token.path.join('_').replace(/[.-]/g, '_');
    const val = token.$value as any;
    const value = val.value;
    const unit = val.unit === 'px' ? 'dp' : val.unit === 'rem' ? 'sp' : 'dp';
    xml += `    <dimen name="${name}">${value}${unit}</dimen>\n`;
  }

  xml += `</resources>\n`;

  return { path: 'values/dimens.xml', content: xml, language: 'xml' };
}

function generateTypographyStyles(ctx: GeneratorContext): GeneratedFile {
  const typoTokens = ctx.tokenSet.tokens.filter(t => t.$type === 'typography');

  let xml = `<?xml version="1.0" encoding="utf-8"?>\n`;
  xml += `<!-- Auto-generated by @ryndesign/generator-android-view -->\n`;
  xml += `<resources>\n`;

  for (const token of typoTokens) {
    const name = token.path.join('_').replace(/[.-]/g, '_');
    const val = token.$value as any;
    const fontSize = parseFloat(val.fontSize) || 16;
    const fontWeight = val.fontWeight;

    xml += `    <style name="TextAppearance_Design_${capitalize(name)}" parent="TextAppearance.MaterialComponents.Body1">\n`;
    xml += `        <item name="android:textSize">${fontSize}sp</item>\n`;

    if (fontWeight) {
      const textStyle = fontWeightToAndroidStyle(fontWeight);
      if (textStyle) {
        xml += `        <item name="android:textStyle">${textStyle}</item>\n`;
      }
      if (fontWeight >= 500) {
        xml += `        <item name="android:textFontWeight">${fontWeight}</item>\n`;
      }
    }

    if (val.lineHeight) {
      const lineHeight = parseFloat(val.lineHeight);
      if (lineHeight) {
        xml += `        <item name="android:lineHeight">${lineHeight}sp</item>\n`;
      }
    }

    if (val.letterSpacing) {
      const letterSpacing = parseFloat(val.letterSpacing);
      if (letterSpacing) {
        // Android letterSpacing is in "em" units
        xml += `        <item name="android:letterSpacing">${(letterSpacing / fontSize).toFixed(4)}</item>\n`;
      }
    }

    xml += `    </style>\n\n`;
  }

  xml += `</resources>\n`;

  return { path: 'values/typography_styles.xml', content: xml, language: 'xml' };
}

function generateThemeAttrs(ctx: GeneratorContext): GeneratedFile {
  const colorTokens = ctx.tokenSet.tokens.filter(t => t.$type === 'color');

  let xml = `<?xml version="1.0" encoding="utf-8"?>\n`;
  xml += `<!-- Auto-generated by @ryndesign/generator-android-view -->\n`;
  xml += `<resources>\n\n`;

  // Declare custom attrs
  xml += `    <declare-styleable name="DesignTokens">\n`;
  for (const token of colorTokens) {
    const name = token.path.join('_').replace(/[.-]/g, '_');
    xml += `        <attr name="design_${name}" format="color" />\n`;
  }
  xml += `    </declare-styleable>\n\n`;

  // Theme overlay with all tokens
  xml += `    <style name="Theme.Design.Overlay" parent="">\n`;
  for (const token of colorTokens) {
    const name = token.path.join('_').replace(/[.-]/g, '_');
    xml += `        <item name="design_${name}">@color/${name}</item>\n`;
  }
  xml += `    </style>\n\n`;

  xml += `</resources>\n`;

  return { path: 'values/attrs_design.xml', content: xml, language: 'xml' };
}

function normalizeHexForAndroid(hex: string): string {
  const cleaned = hex.replace('#', '');
  if (cleaned.length === 6) {
    return `#${cleaned.toUpperCase()}`;
  }
  if (cleaned.length === 8) {
    // RGBA -> ARGB for Android
    const r = cleaned.substring(0, 2);
    const g = cleaned.substring(2, 4);
    const b = cleaned.substring(4, 6);
    const a = cleaned.substring(6, 8);
    return `#${a.toUpperCase()}${r.toUpperCase()}${g.toUpperCase()}${b.toUpperCase()}`;
  }
  return `#${cleaned.toUpperCase()}`;
}

function fontWeightToAndroidStyle(weight: number): string | null {
  if (weight >= 700) return 'bold';
  if (weight >= 400 && weight < 500) return 'normal';
  return null;
}

function capitalize(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1);
}
